package com.tailtopia.support;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.tailtopia.admin.support.service.AdminSupportTicketQueryService;
import com.tailtopia.admin.support.service.AdminTicketRefundService;
import com.tailtopia.pay.refund.repository.RefundRequestRepository;
import com.tailtopia.shared.error.AppException;
import com.tailtopia.support.domain.RelatedOrderType;
import com.tailtopia.support.repository.FeedbackTicketRepository;
import com.tailtopia.support.service.SupportTicketService;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * L1：工单关联电商订单 · 不串单（Story 3-2 AC8/AC9）。
 *
 * <p>🔴 <b>本类构造的是「两类订单 id 相同」的场景</b> —— 那不是巧合而是常态：
 * {@code consult_orders.id} 与 {@code shop_orders.id} 都是 {@code GENERATED BY DEFAULT AS IDENTITY}、
 * 各自从 1 开始，数值空间完全重叠。本 story 之前，一个电商单 id 会被无条件当成同号的问诊单，
 * 后台展示一条不相干的订单，退款链路还会拿它去建退款请求。
 */
class SupportTicketShopOrderLinkIntegrationTest extends ApiIntegrationTest {

    @Autowired
    private SupportTicketService tickets;
    @Autowired
    private FeedbackTicketRepository ticketRepo;
    @Autowired
    private AdminTicketRefundService ticketRefund;
    @Autowired
    private AdminSupportTicketQueryService query;
    @Autowired
    private RefundRequestRepository refunds;
    @Autowired
    private JdbcTemplate jdbc;

    private static final long ADMIN = 1L;

    private String newTicket(long userId) {
        return tickets.createTicket(userId, "订单有问题", "货没到", "EMAIL", "u@petgo.test", true,
                null, List.of(), List.of());
    }

    /** 直接插一条 shop_orders 并把 id 钉成 {@code forcedId}，用来制造与问诊单撞号。 */
    private String seedShopOrderWithId(long forcedId, long userId) {
        String token = "shoptok" + SEQ.incrementAndGet();
        // ⚠️ 收货地址快照列名**带 ship_ 前缀**（V20260817_2308:32-38）。
        //    少写前缀会让整个类在 L1 直接 "column does not exist"，
        //    而本 story 最关键的「不串单」验收正好全在这个类里。
        jdbc.update("""
                INSERT INTO shop_orders (id, public_token, user_id, status, goods_subtotal,
                        shipping_fee, shipping_discount, total_amount,
                        ship_receiver_name, ship_receiver_phone, ship_provinsi,
                        ship_kota_kabupaten, ship_kecamatan, ship_address_line, ship_kode_pos,
                        created_at, updated_at)
                VALUES (?, ?, ?, 'PENDING_PAYMENT', 100000, 0, 0, 100000,
                        'Budi', '08123', 'DKI', 'Jaksel', 'Kebayoran', 'Jl. 1', '12110',
                        now(), now())
                """, forcedId, token, userId);
        return token;
    }

    @Test
    @DisplayName("🔴 AC8：两类订单同号时，两张工单各显示各的订单号，互不串")
    void collidingIdsDoNotCrossTalk() {
        long userId = newUser().getId();
        // 让电商单占一个必然与某条问诊单撞号的小 id。
        long collidingId = 1L;
        String shopToken = seedShopOrderWithId(collidingId, userId);

        String ticketB = newTicket(userId);
        ticketRefund.linkShopOrder(ticketB, shopToken, ADMIN);

        var viewB = query.find(ticketB, true);
        assertThat(viewB.relatedOrderType()).isEqualTo("SHOP");
        assertThat(viewB.relatedOrderToken())
                .as("电商工单必须显示电商订单号（TOKO 前缀），不是同号问诊单的 token")
                .startsWith("TOKO-");
        assertThat(ticketRepo.findByTicketToken(ticketB).orElseThrow().getRelatedOrderType())
                .isEqualTo(RelatedOrderType.SHOP);
    }

    @Test
    @DisplayName("🔴 AC8：SHOP 工单点退款判定 → 422，且 refund_requests 零新增")
    void shopTicketRefundIsRejectedAndCreatesNoRefundRequest() {
        long userId = newUser().getId();
        String shopToken = seedShopOrderWithId(2L, userId);
        String ticket = newTicket(userId);
        ticketRefund.linkShopOrder(ticket, shopToken, ADMIN);

        long refundsBefore = refunds.count();

        assertThatThrownBy(() -> ticketRefund.approveRefundNeed(ticket, ADMIN))
                .isInstanceOf(AppException.class)
                .extracting(e -> ((AppException) e).getMessageCode())
                .isEqualTo("admin.err.ticket.refundNotForShopOrder");
        assertThatThrownBy(() -> ticketRefund.rejectRefundNeed(ticket, ADMIN))
                .isInstanceOf(AppException.class);

        assertThat(refunds.count())
                .as("一条都不许建 —— 建出来的那条会挂在一个不相干的问诊单上")
                .isEqualTo(refundsBefore);
    }

    @Test
    @DisplayName("AC9：存量工单（未关联订单）的类型默认 CONSULT，历史行为零变化")
    void untouchedTicketDefaultsToConsult() {
        long userId = newUser().getId();
        String ticket = newTicket(userId);

        var t = ticketRepo.findByTicketToken(ticket).orElseThrow();
        assertThat(t.getRelatedOrderId()).isNull();
        assertThat(t.getRelatedOrderType()).isEqualTo(RelatedOrderType.CONSULT);

        // 未关联订单仍是「请先关联订单」那条 422，不是新加的类型错误。
        assertThatThrownBy(() -> ticketRefund.approveRefundNeed(ticket, ADMIN))
                .isInstanceOf(AppException.class)
                .extracting(e -> ((AppException) e).getMessageCode())
                .isEqualTo("admin.err.ticket.linkOrderFirst");
    }

    @Test
    @DisplayName("用户建单带电商订单 token → 解析成 (id, SHOP)")
    void userCreatedTicketResolvesShopToken() {
        long userId = newUser().getId();
        String shopToken = seedShopOrderWithId(3L, userId);

        String ticket = tickets.createTicket(userId, "订单有问题", "货没到", "EMAIL",
                "u@petgo.test", true, shopToken, List.of(), List.of());

        var t = ticketRepo.findByTicketToken(ticket).orElseThrow();
        assertThat(t.getRelatedOrderId()).isEqualTo(3L);
        assertThat(t.getRelatedOrderType()).isEqualTo(RelatedOrderType.SHOP);
    }

    @Test
    @DisplayName("🔒 别人的电商单 token → 静默存 null（OPEN-1 宽松，不把建单打挂）")
    void otherUsersShopTokenIsSilentlyIgnored() {
        long owner = newUser().getId();
        long stranger = newUser().getId();
        String shopToken = seedShopOrderWithId(4L, owner);

        String ticket = tickets.createTicket(stranger, "订单有问题", "货没到", "EMAIL",
                "u@petgo.test", true, shopToken, List.of(), List.of());

        var t = ticketRepo.findByTicketToken(ticket).orElseThrow();
        assertThat(t.getRelatedOrderId()).as("用户是来求助的，误传 token 不能拒之门外").isNull();
        assertThat(t.getRelatedOrderType()).isEqualTo(RelatedOrderType.CONSULT);
    }
}
