-- Story 1.1（V1.1.4 社区管控）：隐藏关系表——「某个账号的内容不再展示给某个用户」这件事本身。
-- 它有且只有两个来源：holder 主动拉黑（BLOCK）与 holder 举报后系统自动建立（REPORT）。
-- 六处生效点共用本表：Feed 候选池 / 运营干预位 / 评论 R1·R2 / 搜索话题列表 / 互动通知抑制 / 主页访问。
-- ddl-auto=validate，schema 归 Flyway。UTC。
--
-- ⚠️ 唯一键是三元 (holder_id, target_id, source) 而不是二元——幂等只在同一来源之间成立：
--   已存在 REPORT 行时再发起主动拉黑，必须照常新增 BLOCK 行。写成二元会让用户点了「拉黑」、
--   Toast 说「请在黑名单里查看」，去了却找不到人（决策 C-91）。
-- ⚠️ 六处生效点里只有「主页访问」区分 source（只认 BLOCK，举报隐藏照常放行——那是 FR-58
--   闭环的支点：「已举报」状态与重复举报入口都靠它）。其余五处一律不区分。
-- source：枚举 varchar + UPPER_SNAKE（BLOCK / REPORT），length>1 规避 Hibernate CHAR(1) 坑。
-- 外键 ON DELETE CASCADE：注销级联删除（决策 D1/D2）——用户注销时其两侧关系一并清除。

CREATE TABLE user_hide_relations (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holder_id  BIGINT       NOT NULL,                     -- 不想看见对方的人（users.id）
    target_id  BIGINT       NOT NULL,                     -- 被隐藏的人（users.id）
    source     VARCHAR(16)  NOT NULL,                     -- BLOCK=主动拉黑（可解除）/ REPORT=举报隐藏（永不删）
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),       -- UTC；黑名单页按此倒序，勿改用 updated_at
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),       -- UTC
    CONSTRAINT ck_user_hide_relations_source CHECK (source IN ('BLOCK', 'REPORT')),
    CONSTRAINT uq_user_hide_relations_holder_target_source UNIQUE (holder_id, target_id, source),
    CONSTRAINT fk_user_hide_relations_holder FOREIGN KEY (holder_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_hide_relations_target FOREIGN KEY (target_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 四处读取点的热路径：EXISTS(holder=?, target=?)。holder 前导，与三元唯一键前导列一致。
-- 对照既有先例 V52 为 content_reports 补的 reporter 前导索引——相关子查询需要 holder 前导才走得上。
CREATE INDEX idx_user_hide_relations_holder_target ON user_hide_relations (holder_id, target_id);
