-- V1.4.0 精选自营电商 · Story 1.1 —— 商品与 SKU 建模（FR-94 / FR-94A）。
-- 工作线：V1.4.0 电商（分支 shawn/oneline-ecommerce）· 独占号段 V101–V139（并行契约 §1）。
-- 本迁移【只建新表，不触碰任何共享表】→ 无需在群里认领（对比 3.3 改 payment_intents /
-- 6.1 改 pet_profiles / 6.3 改 ck_notifications_type，那三条必须先认领）。
-- ⚠️ 号序必须与 story 实现顺序一致：Flyway 默认 outOfOrder=false，先跑大号再出现小号会拒绝启动。
--    本 Epic 后续：1.2 → V102。合并 main 时【不重排号】（与决策 E2 的最大差异）。
--
-- 设计要点：
-- · 系统内首次出现【实物商品】——既有收费场景（AI问诊解锁/兽医咨询/PawCoin充值/高清图）全是虚拟商品。
-- · 对外标识一律不可枚举 public_token（CLAUDE.md 护栏）；自增 id 绝不外露，接口只认 token。
-- · 枚举落库 varchar + CHECK（UPPER_SNAKE），不用 DB 原生 enum —— 与 payment_intents(V60) 同范式。
-- · 金额用最小币种单位 BIGINT（IDR 无小数），禁 DECIMAL/double（NFR-9 资金精度）。
-- · feeding_guide 为【结构化 JSONB 数组】，是 FR-109 粮量见底预估的唯一计算依据，绝不接受自由文本。
--   数据本身依赖 DEP-6（首批 SKU 每日建议喂量，责任方 Rendy），未到位时 FR-109 恒不触发（一等路径）。
-- · return_policy 三值【不含「换」】—— 换货已砍出本版本（decision-log C-13）。
-- · 图片只存 OSS objectKey，绝不存 URL / 签名 URL（存储 + 日志双护栏，NFR-5）。
-- · 库存不在本表 —— sku_inventory 属 Story 1.2（V102），此处不预留库存列。

CREATE TABLE shop_products (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token    VARCHAR(32)  NOT NULL,                    -- 不可枚举对外标识（Base62 22 位）
    name            VARCHAR(60)  NOT NULL,                    -- FR-94 ①
    brand           VARCHAR(60)  NOT NULL,                    -- FR-94 ②
    category        VARCHAR(24)  NOT NULL,                    -- FR-94 ③ MAKANAN|OBAT_VITAMIN|CAMILAN|PERAWATAN
    main_image_key  VARCHAR(255) NOT NULL,                    -- FR-94 ④ 主图：OSS objectKey，非 URL
    gallery_keys    JSONB,                                    -- FR-94 ④ 图集 ≤8：objectKey 列表
    -- FR-94 ⑤ 规格列表 → shop_skus 表，不是本表的列
    species         VARCHAR(16)  NOT NULL,                    -- FR-94 ⑥ DOG|CAT|UNIVERSAL（FR-107 硬过滤依据）
    body_size       VARCHAR(16),                              -- FR-94 ⑦ SMALL|MEDIUM|LARGE|UNIVERSAL
    age_stage       VARCHAR(16),                              -- FR-94 ⑧ PUPPY|ADULT|SENIOR|UNIVERSAL
    detail_html     TEXT         NOT NULL,                    -- FR-94 ⑨ 富文本（含成分表）
    feeding_guide   JSONB,                                    -- FR-94 ⑩ [{weightMinKg,weightMaxKg,gramsPerDay}]
    shelf_life_note VARCHAR(120) NOT NULL,                    -- FR-94 ⑪ 保质期说明（展示文案）
    return_policy   VARCHAR(24)  NOT NULL
                                 DEFAULT 'NO_RETURN_AFTER_OPEN', -- FR-94 ⑫ 默认取安全侧（后台 §2）
    sort_weight     INT          NOT NULL DEFAULT 0,          -- 运营精选排序（维护逻辑属 1.5）
    is_active       BOOLEAN      NOT NULL DEFAULT FALSE,      -- 上下架（维护逻辑属 1.5）；新建默认未上架
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_shop_products_category CHECK (category IN
        ('MAKANAN', 'OBAT_VITAMIN', 'CAMILAN', 'PERAWATAN')),
    CONSTRAINT ck_shop_products_species CHECK (species IN
        ('DOG', 'CAT', 'UNIVERSAL')),
    CONSTRAINT ck_shop_products_body_size CHECK (body_size IS NULL OR body_size IN
        ('SMALL', 'MEDIUM', 'LARGE', 'UNIVERSAL')),
    CONSTRAINT ck_shop_products_age_stage CHECK (age_stage IS NULL OR age_stage IN
        ('PUPPY', 'ADULT', 'SENIOR', 'UNIVERSAL')),
    -- 三值不含「换」：换货已砍（C-13）。运营标出平台无法兑现的承诺，比少一个选项危险得多。
    CONSTRAINT ck_shop_products_return_policy CHECK (return_policy IN
        ('RETURNABLE', 'NO_RETURN_AFTER_OPEN', 'NON_RETURNABLE'))
);

CREATE UNIQUE INDEX uq_shop_products_token    ON shop_products (public_token);
CREATE INDEX        idx_shop_products_listing ON shop_products (category, sort_weight DESC, id DESC);

COMMENT ON COLUMN shop_products.feeding_guide IS
    '每日建议喂量：[{weightMinKg,weightMaxKg,gramsPerDay}]。FR-109 粮量见底预估的唯一计算依据，禁自由文本。';
COMMENT ON COLUMN shop_products.main_image_key IS 'OSS objectKey，非 URL（禁存签名 URL）。';

CREATE TABLE shop_skus (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token   VARCHAR(32) NOT NULL,                      -- 不可枚举对外标识
    product_id     BIGINT      NOT NULL REFERENCES shop_products (id) ON DELETE CASCADE,
    spec_name      VARCHAR(40) NOT NULL,                      -- 规格名，如「3 kg」
    price          BIGINT      NOT NULL,                      -- 最小币种单位（IDR 无小数）；禁 DECIMAL
    net_weight_g   BIGINT,                                    -- 净含量（克）；FR-109 计算用，非 Makanan 可空
    return_policy  VARCHAR(24),                               -- 可空 = 继承商品级（FR-94A）
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_shop_skus_price          CHECK (price >= 0),
    CONSTRAINT ck_shop_skus_net_weight     CHECK (net_weight_g IS NULL OR net_weight_g > 0),
    CONSTRAINT ck_shop_skus_return_policy  CHECK (return_policy IS NULL OR return_policy IN
        ('RETURNABLE', 'NO_RETURN_AFTER_OPEN', 'NON_RETURNABLE'))
);

CREATE UNIQUE INDEX uq_shop_skus_token   ON shop_skus (public_token);
CREATE INDEX        idx_shop_skus_product ON shop_skus (product_id, id);

COMMENT ON COLUMN shop_skus.price IS '最小币种单位整型（IDR 无小数）。禁 DECIMAL/double —— 资金精度护栏 NFR-9。';
COMMENT ON COLUMN shop_skus.return_policy IS '可空：为空则继承 shop_products.return_policy（FR-94A）。';
