-- Story 2.1（V1.1.4 社区管控）：账号举报的工单表 + 明细表。
-- 工单粒度 = 被举报账号（target_user_id 唯一）：同一个人被 12 个用户举报，也只有一条工单。
-- 明细每次追加、绝不覆盖：每一次举报的类型与「其他」补充说明都要留住，运营才看得到「这个人怎么被举报的」。
-- ddl-auto=validate，schema 归 Flyway。UTC。
--
-- ⚠️ 与既有内容举报 content_reports 的关键差异（照抄那张表会直接做错）：
--   content_reports 的唯一键是 (reporter_id, post_id)，同一人重复举报被 service 幂等吞掉、什么都不写；
--   账号举报**必须反过来**——同一人可无限次举报同一账号，每次都落一行明细（PRD FR-58 重复举报第 2/3 条）。
--   唯一约束因此只加在工单表的 target_user_id 上，**明细表没有任何唯一约束**。
-- ⚠️ 不设频率限制 / 冷却窗口（A-A23，主动决定）：单个举报人对优先级分的贡献已由公式封顶 2 分。
--   service 层只有一道**秒级**去重，防的是双击穿透与网络重试，不是限制用户意图。
-- ⚠️ 零自动预处置（AD-17）：无论多少人举报，都不会自动挂起该账号的内容。既有帖子级的两条自动通道
--   （ILLEGAL 单次触发 / 举报人数≥10）只作用于 content_reports，本版本一行未改。

CREATE TABLE account_reports (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id    BIGINT       NOT NULL,               -- 被举报的账号（users.id）；一人一工单
    status            VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    first_reported_at TIMESTAMPTZ  NOT NULL DEFAULT now(), -- 首次被举报时刻；工单翻回待处理时**不刷新**
    handled_by        BIGINT,                              -- 处置人（admins.id）；未处置为 NULL
    handled_at        TIMESTAMPTZ,                         -- 处置时刻；未处置为 NULL
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(), -- UTC
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(), -- UTC
    -- DISMISSED 在运营后台展示为**「无需处置」**（中性词，C-103），不叫「已驳回」——
    -- 数据层保留 DISMISSED 语义，改的只是展示层文案，别顺手把这个值也改了。
    CONSTRAINT ck_account_reports_status CHECK (status IN ('PENDING', 'RESOLVED', 'DISMISSED')),
    CONSTRAINT uq_account_reports_target_user UNIQUE (target_user_id),
    CONSTRAINT fk_account_reports_target FOREIGN KEY (target_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE account_report_entries (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id   BIGINT       NOT NULL,                     -- 所属工单
    reporter_id BIGINT       NOT NULL,                     -- 举报人（users.id）
    reason      VARCHAR(24)  NOT NULL,                     -- 账号维度五类（≠ 内容维度的 ReportReason）
    detail      VARCHAR(200),                              -- 仅 OTHER 必填；⚠️ 用户自由文本，禁止进日志
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),       -- UTC
    -- 账号维度五类：与内容维度的 ILLEGAL/MISINFO/INAPPROPRIATE/HARASSMENT/OTHER **只有两项对得上**，
    -- 是另一套枚举，别复用（AD-12）。
    CONSTRAINT ck_account_report_entries_reason
        CHECK (reason IN ('SPAM', 'IMPERSONATION', 'HARASSMENT', 'VIOLATING_CONTENT', 'OTHER')),
    CONSTRAINT fk_account_report_entries_report FOREIGN KEY (report_id)
        REFERENCES account_reports (id) ON DELETE CASCADE,
    CONSTRAINT fk_account_report_entries_reporter FOREIGN KEY (reporter_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- Epic 3 的优先级公式要一次聚合出「多少人报过 / 一共报了多少次 / 其中几个人报了≥5 次」，
-- 三个数全靠 (report_id, reporter_id) 这一对分组。前导列 report_id 与按工单取明细的路径一致。
CREATE INDEX idx_account_report_entries_report_reporter
    ON account_report_entries (report_id, reporter_id);
