-- Story 3.1（V1.1.4 社区管控）：账号级处置记录表。
-- 一行 = 对某个账号执行过的一次处置（警告 / 封号）。运营在工单里要看到「这个人以前被处置过几次」，
-- 而在此之前**账号级处置没有任何结构化留痕** —— 只有 admin_audit_logs 里的一行中文 detail，
-- 想数「他被警告过几次」得去正则匹配那段文字。这正是本表的立项理由。
-- ddl-auto=validate，schema 归 Flyway。UTC。
--
-- ⚠️ 本 story 只**读**这张表（工单列表要显示历史处置次数），**写入由 Story 3.2 接入**。
--   所以上线初期表为空、次数显示 0 —— 那是逻辑完整状态，不是没做完。
-- report_id 可空：处置不一定由某条工单触发（也可能是运营主动巡查），所以不设 NOT NULL。

CREATE TABLE account_disposals (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id BIGINT       NOT NULL,               -- 被处置的账号（users.id）
    disposal_type  VARCHAR(16)  NOT NULL,               -- WARNING=警告 / SUSPEND=封号
    operator_id    BIGINT,                              -- 处置人（admin_accounts.id）；系统自动处置为 NULL
    report_id      BIGINT,                              -- 触发本次处置的账号举报工单（可空）
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(), -- UTC
    CONSTRAINT ck_account_disposals_type CHECK (disposal_type IN ('WARNING', 'SUSPEND')),
    CONSTRAINT fk_account_disposals_target FOREIGN KEY (target_user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_account_disposals_report FOREIGN KEY (report_id)
        REFERENCES account_reports (id) ON DELETE SET NULL
);

-- 「这个账号历史被处置过几次 / 最近一次是什么时候」——工单列表与详情都按这个方向查。
CREATE INDEX idx_account_disposals_target_created
    ON account_disposals (target_user_id, created_at DESC);
