-- V1.4.0 精选自营电商 · Story 3.2 —— 电商订单（FR-102 / AD-7 / AD-13）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。本迁移【只建新表】→ 无需群里认领。
-- ⚠️ epics 原文写 V105，但按台账重排后取 V109。
--
-- 🔴【订单号 = SecureRandom + Base62 22 位 token，绝不可枚举】（AD-7 / NFR-3 / CLAUDE.md 护栏）
--    ⚠️ 尤其【不用 TT + YYYYMMDD + 序列】——那同样可枚举：任何用户从自己的订单号
--    即可推断平台当日单量与累计单量。对一个还在验证 A-15 的产品，这是直接泄露最敏感的经营数据。
--    对账所需的连续序号走独立内部序列 seq_no，【不外露】。
--
-- 🔴【收货地址存快照，不存地址簿外键】（AD-13）
--    用户改地址簿不得改写历史订单的履约地址——快递已按旧地址发出，
--    订单上的地址是【履约凭证】，不是【当前偏好】。这两件事被混为一谈时，
--    纠纷里没人说得清货到底该寄到哪。

CREATE TABLE shop_orders (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 🔴 对外展示的订单号；不可枚举
    public_token       VARCHAR(32)  NOT NULL,
    -- 对账用连续序号，【不外露】
    seq_no             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT       NOT NULL REFERENCES users (id),

    status             VARCHAR(32)  NOT NULL,

    -- 金额（最小币种单位，IDR 无小数）
    goods_subtotal     BIGINT       NOT NULL,
    shipping_fee       BIGINT       NOT NULL DEFAULT 0,
    shipping_discount  BIGINT       NOT NULL DEFAULT 0,   -- 免运抵扣，≤ 0
    total_amount       BIGINT       NOT NULL,

    -- 🔒 收货地址【快照】（AD-13）。含 PII：姓名/电话/详细地址，日志禁记。
    ship_receiver_name   VARCHAR(40)  NOT NULL,
    ship_receiver_phone  VARCHAR(16)  NOT NULL,
    ship_provinsi        VARCHAR(60)  NOT NULL,
    ship_kota_kabupaten  VARCHAR(60)  NOT NULL,
    ship_kecamatan       VARCHAR(60)  NOT NULL,
    ship_address_line    VARCHAR(120) NOT NULL,
    ship_kode_pos        VARCHAR(5)   NOT NULL,

    -- ⚠️ 以下三列由 Epic 5 使用，在 Epic 3 建表时一并创建（IR 已登记的有意偏离）：
    --    同一张表、可空/DEFAULT 0、Epic 3 期间恒为初值、不影响任何行为；
    --    随建表一次写完远低于 Epic 5 再起 ALTER 的成本。若 Epic 5 被取消，它们是无害死字段。
    refunded_total     BIGINT       NOT NULL DEFAULT 0,   -- AD-2 整数累计法的持久化依据
    refunded_coin      BIGINT       NOT NULL DEFAULT 0,
    is_full_return     BOOLEAN      NOT NULL DEFAULT FALSE, -- FR-104A 去程运费判定

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_shop_orders_token UNIQUE (public_token),
    -- 八态。Epic 3 只实现「待支付 → 待发货」段；其余态由 Epic 4/5 接入，
    -- 但 CHECK 一次写全——枚举值缺失会让后续 Epic 的迁移变成改约束而不是加代码。
    CONSTRAINT ck_shop_orders_status CHECK (status IN (
        'PENDING_PAYMENT', 'PENDING_SHIPMENT', 'SHIPPED', 'DELIVERED',
        'COMPLETED', 'CANCELLED', 'REFUNDING', 'REFUNDED')),
    CONSTRAINT ck_shop_orders_amounts CHECK (
        goods_subtotal >= 0 AND shipping_fee >= 0 AND shipping_discount <= 0
        AND total_amount >= 0),
    CONSTRAINT ck_shop_orders_refund_non_negative CHECK (
        refunded_total >= 0 AND refunded_coin >= 0)
);

CREATE INDEX ix_shop_orders_user ON shop_orders (user_id, created_at DESC);
CREATE INDEX ix_shop_orders_status ON shop_orders (status, created_at DESC);

CREATE TABLE shop_order_lines (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT       NOT NULL REFERENCES shop_orders (id) ON DELETE CASCADE,
    sku_id         BIGINT       NOT NULL REFERENCES shop_skus (id),

    -- 🔴 商品信息同样【快照】：商品改名改价、SKU 下架都不得改写历史订单。
    product_name   VARCHAR(120) NOT NULL,
    spec_name      VARCHAR(60)  NOT NULL,
    unit_price     BIGINT       NOT NULL,
    qty            INT          NOT NULL,
    line_total     BIGINT       NOT NULL,
    -- 退货规则也快照：下单时承诺的是什么，退货时就按什么算（FR-104）
    return_policy  VARCHAR(32)  NOT NULL,

    -- Epic 5 用（同上，随建表一并创建）
    refunded_qty   INT          NOT NULL DEFAULT 0,

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_shop_order_lines_qty CHECK (qty > 0),
    CONSTRAINT ck_shop_order_lines_amounts CHECK (unit_price >= 0 AND line_total >= 0),
    CONSTRAINT ck_shop_order_lines_refunded CHECK (refunded_qty >= 0 AND refunded_qty <= qty)
);

CREATE INDEX ix_shop_order_lines_order ON shop_order_lines (order_id, id);

COMMENT ON TABLE shop_orders IS
    '电商订单（Story 3.2）。🔴 public_token 不可枚举；🔒 收货地址为快照非外键（AD-13）。';
COMMENT ON COLUMN shop_orders.seq_no IS
    '对账用连续序号，【绝不外露】——外露即等于给出可枚举的订单标识。';
COMMENT ON COLUMN shop_orders.ship_receiver_phone IS
    '🔒 PII。履约地址快照的一部分，日志禁记。';
