-- V1.4.0 精选自营电商 · Story 4.1 —— 履约段：包裹表 + 订单履约时刻（SPEC-2 / S-1 / S-2 / FR-102）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。【只建新表 + 只给自家表加列】→ 无需群里认领。
-- ⚠️ epics 原文把 shipments 记在 Story 4.2 的 V107；按台账「取最大号 +1」实取 V115，
--    且提前到 4.1 —— 4.1 的 AC 写死「订单转 DELIVERED 的条件 = 所有包裹都送达」，
--    没有 shipments 这条判定就无处落地。4.2 因此不再需要迁移。已回写 sprint-status。
--
-- 🔴【一单多包】（S-2）：一个订单 1..N 个包裹，每包自带承运商 / 单号 / 成本 / 送达时刻。
--    订单转 DELIVERED 的条件是【所有】包裹都送达；7 日自动确认以【最后一个】包裹送达为起点。
--    单包裹是多包裹的特例，不为它另开一条路径——两条路径迟早在部分发货时打架。
--
-- 🔴【SPEC-5 补齐：「签收」= 订单进入 DELIVERED 的时刻】。该词在 PRD 里出现四次却既不在术语表
--    也不是状态名。不定义它，Epic 5 的「签收起 7 日退货窗口」在实现层就没有起算点。
--    故 delivered_at 是退货窗口的唯一权威锚点，【自动确认收货不清空它】。
--
-- 🔒 tracking_no 非 PII、可记日志（NFR-5）；同上下文的收件人姓名/电话/详细地址严禁记录。

CREATE TABLE shipments (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_order_id  BIGINT       NOT NULL REFERENCES shop_orders (id) ON DELETE CASCADE,

    -- 承运商三选一（C-14 后运费表已是区域一维，承运商【不是运费维度】，仅在发货时选择并留痕）
    carrier        VARCHAR(16)  NOT NULL,
    tracking_no    VARCHAR(64)  NOT NULL,
    -- S-11 承运成本：运单实际金额。不录则 AB-13A 毛利缺行、假设 A-19 不可验证。
    carrier_cost   BIGINT       NOT NULL DEFAULT 0,

    status         VARCHAR(16)  NOT NULL,
    shipped_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    delivered_at   TIMESTAMPTZ,

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_shipments_carrier CHECK (carrier IN ('JNE', 'SICEPAT', 'ANTERAJA')),
    CONSTRAINT ck_shipments_status  CHECK (status IN ('SHIPPED', 'DELIVERED')),
    CONSTRAINT ck_shipments_cost    CHECK (carrier_cost >= 0),
    -- 🔴 状态与时刻必须同步：DELIVERED 必有送达时刻，未送达必无。
    --    两者脱节时，「所有包裹都送达」与「最后一个包裹的送达时刻」会给出互相矛盾的答案。
    CONSTRAINT ck_shipments_delivered_at CHECK (
        (status = 'DELIVERED') = (delivered_at IS NOT NULL))
);

CREATE INDEX ix_shipments_order ON shipments (shop_order_id, id);
-- 同一承运商的同一运单号不该出现两次（重复录入会让承运成本被重复计入毛利）
CREATE UNIQUE INDEX uq_shipments_carrier_tracking ON shipments (carrier, tracking_no);

-- ---------- 订单履约时刻 ----------
ALTER TABLE shop_orders
    ADD COLUMN shipped_at        TIMESTAMPTZ,
    ADD COLUMN delivered_at      TIMESTAMPTZ,
    ADD COLUMN completed_at      TIMESTAMPTZ,
    -- 🔴 SPEC-2 的三条出口各自留痕：缺任一条都会死锁，出了问题要能查出走的是哪条
    ADD COLUMN delivery_source   VARCHAR(24),
    ADD COLUMN completion_source VARCHAR(24);

ALTER TABLE shop_orders
    ADD CONSTRAINT ck_shop_orders_delivery_source CHECK (
        delivery_source IS NULL OR delivery_source IN (
            'SHIPMENTS_ALL_DELIVERED', 'ADMIN_MARK', 'USER_CONFIRM', 'AUTO_TIMEOUT')),
    ADD CONSTRAINT ck_shop_orders_completion_source CHECK (
        completion_source IS NULL OR completion_source IN ('USER_CONFIRM', 'AUTO_TIMEOUT'));

-- 自动确认收货扫描的驱动索引（SHIPPED 超 M 日 → DELIVERED；DELIVERED 超 7 日 → COMPLETED）
CREATE INDEX ix_shop_orders_shipped_at   ON shop_orders (status, shipped_at)
    WHERE status = 'SHIPPED';
CREATE INDEX ix_shop_orders_delivered_at ON shop_orders (status, delivered_at)
    WHERE status = 'DELIVERED';

COMMENT ON TABLE shipments IS
    '包裹（Story 4.1，S-2 一单多包）。订单转 DELIVERED 需全部行 delivered。';
COMMENT ON COLUMN shipments.tracking_no IS
    '物流单号。非 PII，可记日志；同上下文的收件人姓名/电话/地址严禁记录（NFR-5）。';
COMMENT ON COLUMN shipments.carrier_cost IS
    'S-11 承运成本（运单实际金额）。AB-13A 毛利口径依赖本列。';
COMMENT ON COLUMN shop_orders.delivered_at IS
    '🔴 SPEC-5：「签收」= 订单进入 DELIVERED 的时刻。Epic 5 的 7 日退货窗口以此起算，'
    '自动确认收货【不清空】本列。';
