-- V1.4.0 精选自营电商 · Story 5.1 —— 退货申请与行级部分退货（FR-104A / C-12 / AD-5 / S-7 / S-8）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。【只建新表 + 只给自家表加列】→ 无需群里认领。
-- ⚠️ epics 原文写 V108；按台账「取最大号 +1」实取 V118（V115~V117 已被 4.1/4.2/4.4 用掉）。
--
-- 🔴【一张申请承载 1..N 行】（FR-104A / C-12 / AD-5），不是「一单一行」。
--    写成一单一行，部分退货就只能靠「拆成多张申请」表达，而 C-12 又要求同订单
--    只能有一张进行中申请 —— 两条规则会直接打架。
--
-- 🔴【同订单只能有一张进行中申请：用 DB 部分唯一索引强制】（AD-5 / NFR-1）。
--    不靠应用层判断、不用任何锁：应用层的「查一下有没有」与「插入」之间永远有窗口，
--    两个并发请求都能查到「没有」。部分唯一索引把这件事交给数据库，是唯一无窗口的做法。
--
-- 🔴【退款单状态独立于订单状态机】（AD-5）。部分退款完成时订单主状态【不变】；
--    仅当该订单全部行的退款均达 REFUNDED，系统才回写订单为 REFUNDED。
--    ⚠️ 后台 PRD 原写「退款执行状态需与订单状态联动」—— 照字面实现会让退了一行的订单
--    被整单标记为已退款，连带毁掉 AB-13A 售后成本与 AB-13D 对账。

CREATE TABLE return_requests (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 🔴 对外标识不可枚举（NFR-3）
    public_token      VARCHAR(32)  NOT NULL,
    shop_order_id     BIGINT       NOT NULL REFERENCES shop_orders (id) ON DELETE CASCADE,
    user_id           BIGINT       NOT NULL REFERENCES users (id),

    status            VARCHAR(24)  NOT NULL,
    return_type       VARCHAR(24)  NOT NULL,

    -- 🔴 由勾选范围【自动得出】，不给客服手工开关（C-12）——
    --    手工可调等于打开「凑单免运 → 退掉凑单商品」的套利口子。
    is_full_return    BOOLEAN      NOT NULL,

    -- 运费归属。🔴「是否批准退货」与「运费由谁承担」是【两件事】，分开记录（AB-12A）。
    --    回程（寄回）运费归属由退货类型决定；去程运费是否退由 is_full_return 决定。
    return_ship_bearer VARCHAR(16),                 -- PLATFORM / USER，审核时判定
    outbound_fee_refundable BOOLEAN NOT NULL DEFAULT FALSE,   -- 去程运费是否退（= is_full_return）

    reason_note       VARCHAR(500),
    -- 凭证图 ≤6 张，存对象存储 key，逗号分隔（V1 不为它单开一张表）
    evidence_keys     VARCHAR(1000),

    -- 审核
    reviewed_by       BIGINT,
    reviewed_at       TIMESTAMPTZ,
    reject_reason     VARCHAR(500),

    -- 寄回（S-7 用户自寄；🔴 不做上门取件）
    shipback_deadline TIMESTAMPTZ,                  -- 超 7 日未寄回 → CLOSED
    shipback_carrier  VARCHAR(16),
    shipback_tracking_no VARCHAR(64),
    shipback_fee      BIGINT,                       -- 用户垫付的实际运单金额（平台承担时一并返还）

    -- 质检（S-10：驳回不是纯终态，须能展示处置方式）
    inspection_passed BOOLEAN,
    inspection_note   VARCHAR(500),
    inspection_photo_keys VARCHAR(1000),
    reject_disposal   VARCHAR(16),                  -- RETURN_TO_USER / WRITE_OFF
    return_ship_back_tracking_no VARCHAR(64),       -- 退回用户时的回寄单号（运费平台承担）

    -- 退款执行
    refund_amount     BIGINT,                       -- 本申请应退总额（含运费部分）
    refund_coin       BIGINT,                       -- 其中 PawCoin 段（AD-2 整数累计法算出）
    refund_cash       BIGINT,                       -- 其中现金段 = refund_amount - refund_coin
    compensation_premium BIGINT NOT NULL DEFAULT 0, -- 平台责任补偿溢价（C-9，读独立配置项）
    refund_attempts   INT          NOT NULL DEFAULT 0,   -- S-8 ③：失败可重试，超 3 次转人工
    refund_failure_note VARCHAR(500),
    refunded_at       TIMESTAMPTZ,

    -- 现金段去向（Story 5.8 用户二选一）。🔴 PawCoin 段【没有】对应字段 ——
    -- 那不是遗漏：FR-100A 规则 1 要求「PawCoin 段退成真钱」这条路在数据模型里就不存在。
    cash_destination  VARCHAR(16),                  -- TO_BANK / TO_PAWCOIN
    -- 🔴 零改动复用 pay/refund 的 PayoutChannel：BCA(0) / OVO(2500) / GOPAY(2500)，
    --    与 FR-105 费率表逐字一致。⚠️ 但【不复用 refund_requests 表】——
    --    它的 order_id 外键指向 consult_orders 且一订单一请求（AD-10：两个不同的东西）。
    payout_channel    VARCHAR(16),
    payout_account    VARCHAR(255),                 -- 🔒 PII：加密列（EncryptedStringConverter）
    payout_account_holder VARCHAR(255),             -- 🔒 PII：加密列
    payout_channel_fee BIGINT,
    -- 平台承担回程运费时按实际运单金额返还（S-7）。独立于 refund_amount：
    -- 它不是订单里的钱，不能参与 AD-2 的两段拆分（拆分的分母是订单总额）。
    shipback_reimbursed BIGINT NOT NULL DEFAULT 0,
    -- 现金段转 PawCoin 时的【激励】溢价（C-1 反套利）。🔴 与补偿溢价是两个独立配置项（C-9/D-8）。
    incentive_premium BIGINT NOT NULL DEFAULT 0,

    -- 🔴 S-8 ②：驳回后订单要回到【驳回前】的状态，故必须记下它。
    --    不记的话，一张被驳回的拒收申请只能靠猜把订单放回 SHIPPED 还是 PENDING_SHIPMENT。
    order_status_before VARCHAR(32),

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_return_requests_token UNIQUE (public_token),
    -- 7 态：6 态 + CLOSED（超时未寄回）+ REFUND_FAILED（S-8 ③ 新增中间态）
    CONSTRAINT ck_return_requests_status CHECK (status IN (
        'PENDING_REVIEW', 'REJECTED', 'AWAIT_SHIPBACK', 'INSPECTING',
        'REFUNDING', 'REFUNDED', 'REFUND_FAILED', 'CLOSED', 'WITHDRAWN')),
    CONSTRAINT ck_return_requests_type CHECK (return_type IN (
        'QUALITY_ISSUE', 'NON_QUALITY_ISSUE', 'REFUSED_ON_DELIVERY', 'CANCEL_BEFORE_SHIPMENT')),
    CONSTRAINT ck_return_requests_bearer CHECK (
        return_ship_bearer IS NULL OR return_ship_bearer IN ('PLATFORM', 'USER')),
    CONSTRAINT ck_return_requests_disposal CHECK (
        reject_disposal IS NULL OR reject_disposal IN ('RETURN_TO_USER', 'WRITE_OFF')),
    CONSTRAINT ck_return_requests_amounts CHECK (
        (refund_amount IS NULL OR refund_amount >= 0)
        AND (refund_coin IS NULL OR refund_coin >= 0)
        AND (refund_cash IS NULL OR refund_cash >= 0)
        AND compensation_premium >= 0
        AND (shipback_fee IS NULL OR shipback_fee >= 0)),
    -- 两段之和必须等于总额 —— 这条不变式在库级钉死，服务层算错会当场插不进去
    CONSTRAINT ck_return_requests_split CHECK (
        refund_amount IS NULL OR refund_coin IS NULL OR refund_cash IS NULL
        OR refund_coin + refund_cash = refund_amount),
    CONSTRAINT ck_return_requests_attempts CHECK (refund_attempts >= 0),
    CONSTRAINT ck_return_requests_cash_dest CHECK (
        cash_destination IS NULL OR cash_destination IN ('TO_BANK', 'TO_PAWCOIN')),
    CONSTRAINT ck_return_requests_payout_channel CHECK (
        payout_channel IS NULL OR payout_channel IN ('BCA', 'OVO', 'GOPAY')),
    CONSTRAINT ck_return_requests_extra_amounts CHECK (
        shipback_reimbursed >= 0 AND incentive_premium >= 0
        AND (payout_channel_fee IS NULL OR payout_channel_fee >= 0))
);

-- 🔴🔴 【C-12 并发约束的唯一实现】：同一订单在「进行中」的申请至多一张。
--    进行中 = 还会改动这笔订单的钱或货的状态。REJECTED / REFUNDED / CLOSED / WITHDRAWN
--    都已尘埃落定，不参与互斥 —— 否则用户被驳回一次就永远不能再申请了。
CREATE UNIQUE INDEX uq_return_requests_active_per_order
    ON return_requests (shop_order_id)
    WHERE status IN ('PENDING_REVIEW', 'AWAIT_SHIPBACK', 'INSPECTING', 'REFUNDING',
                     'REFUND_FAILED');

CREATE INDEX ix_return_requests_user ON return_requests (user_id, created_at DESC);
CREATE INDEX ix_return_requests_status ON return_requests (status, created_at DESC);

CREATE TABLE return_lines (
    id                BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id BIGINT  NOT NULL REFERENCES return_requests (id) ON DELETE CASCADE,
    -- 🔴 指向订单【行】而不是 SKU：同一个 SKU 可能在一张订单里出现两行（不同价快照）
    order_line_id     BIGINT  NOT NULL REFERENCES shop_order_lines (id),
    qty               INT     NOT NULL,
    -- 该行应退的商品金额（不含运费），按下单时的行单价快照算
    line_refund_amount BIGINT NOT NULL,

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_return_lines_qty CHECK (qty > 0),
    CONSTRAINT ck_return_lines_amount CHECK (line_refund_amount >= 0),
    -- 同一张申请里同一订单行只能出现一次（要退两件就把 qty 写 2）
    CONSTRAINT uq_return_lines_request_line UNIQUE (return_request_id, order_line_id)
);

CREATE INDEX ix_return_lines_request ON return_lines (return_request_id, id);

-- ---------- S-7：退货收件地址（AB-11C 增配一项） ----------
-- 🔴 用户【自寄】到这个地址；不做上门取件（需承运商 API 与商务账号，本版本不接）。
ALTER TABLE shipping_settings
    ADD COLUMN return_address_text VARCHAR(300),
    ADD COLUMN return_receiver_name VARCHAR(60),
    ADD COLUMN return_receiver_phone VARCHAR(20);

COMMENT ON TABLE return_requests IS
    '退货申请（Story 5.1）。🔴 一张承载 1..N 条 return_lines；同订单进行中至多一张（部分唯一索引）。';
COMMENT ON COLUMN return_requests.is_full_return IS
    '🔴 由勾选范围自动得出，不给客服手工开关（C-12）——手工可调等于打开凑单-退货套利的口子。';
COMMENT ON COLUMN return_requests.payout_account IS
    '🔒 PII：收款账号，应用层加密列。绝不记日志、绝不进审计摘要。';
COMMENT ON COLUMN return_requests.order_status_before IS
    '🔴 S-8 ②：驳回后订单要回到驳回前状态，故必须记下它。';
COMMENT ON COLUMN shipping_settings.return_address_text IS
    'S-7 退货收件地址。用户自寄到此处；🔴 本版本不做上门取件。';
