-- V1.4.0 精选自营电商 · Story 1.4 —— 库存流水（后台 AB-10C）。
-- 工作线：V1.4.0 电商（分支 shawn/oneline-ecommerce）· 独占号段 V101–V139（并行契约 §1）。
-- 本迁移【只建新表，不触碰任何共享表】→ 无需在群里认领。
--
-- 补齐 SPEC-7 指出的缺口：在本表之前，actual 除 Story 1.2 的 restock 原语外没有任何业务入口，
-- 即「可售库存的唯一来源是退货质检通过」——库存只能靠退货凭空产生。
--
-- 设计要点：
-- · 🔴【库存增减只能经由一条流水产生】——AB-10C 明令不提供直接编辑库存数字的入口。
--   直接改数会使库存与采购成本脱钩，令 AB-13A 毛利核算失真。
-- · 一张 append-only 流水表同时承担【入库单 / 报损单 / 盘点单 / 审计前后值】四个职责：
--   三类操作要留存的都是同一组字段（操作人·原因·前后值），拆多表会让 AB-13D 对账
--   （进货成本 → 销售收入 → 毛利的可追溯链路）需要 union。
-- · 🔴 本表【不落 locked】——locked 只由订单流程改动（3.4 锁定 / 3.8 出库 / 3.4 释放），
--   与本 Story 的四条路径无关。冗余存储会产生第二个真相。
-- · 🔴 超卖的真实来源在这里（决策 S-3）：「真正的超卖来源是盘点/报损/退货入库撤销，不是并发」。
--   并发那一半已由 V102 的条件原子写解决；本表打开的是另一半，故 CHECK 写得比一般表严。

CREATE TABLE inventory_movements (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id              BIGINT      NOT NULL REFERENCES shop_skus (id) ON DELETE CASCADE,

    -- PURCHASE_INBOUND 采购入库 · RETURN_INBOUND 退货入库批次 · DAMAGE 报损 · STOCKTAKE 盘点调整
    movement_type       VARCHAR(32) NOT NULL,

    -- 🔴 带符号：入库为正、报损为负、盘点为差值（可正可负，可为 0）
    qty_delta           BIGINT      NOT NULL,
    actual_before       BIGINT      NOT NULL,
    actual_after        BIGINT      NOT NULL,

    reason              VARCHAR(500),          -- 报损/盘点必填；入库可空
    purchase_no         VARCHAR(64),           -- 采购单号；退货入库时填原订单号（S-9）
    supplier            VARCHAR(200),          -- 供应商；退货入库可空
    cost_price          BIGINT,                -- 🔒 进货单价（最小币种单位）。商业敏感，需 shop.cost_view
    inbound_date        DATE,                  -- 入库日期

    -- 🔴 服务端从登录态取，绝不接受前端传入
    operator_account_id BIGINT      NOT NULL REFERENCES admin_accounts (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_inventory_movements_type CHECK (
        movement_type IN ('PURCHASE_INBOUND', 'RETURN_INBOUND', 'DAMAGE', 'STOCKTAKE')),

    -- 🔴 让「流水与实际对不上」在 DB 层就写不进去
    CONSTRAINT ck_inventory_movements_delta_consistent CHECK (
        actual_after = actual_before + qty_delta),
    CONSTRAINT ck_inventory_movements_non_negative CHECK (
        actual_before >= 0 AND actual_after >= 0),

    -- 🔴 S-9：入库单的采购单号与进货单价【不允许留空】。
    --   留空会让「钱已退、货已回、系统里不存在」，并污染 AB-13C 的资金占用读数。
    --   拒收货同样必填：采购单号填原订单号、单价取该 SKU 最近一次采购入库单价。
    CONSTRAINT ck_inventory_movements_inbound_required CHECK (
        movement_type NOT IN ('PURCHASE_INBOUND', 'RETURN_INBOUND')
        OR (purchase_no IS NOT NULL AND cost_price IS NOT NULL AND cost_price >= 0)),

    -- 入库方向恒为正；报损方向恒为负（盘点不限，可增可减）
    CONSTRAINT ck_inventory_movements_inbound_positive CHECK (
        movement_type NOT IN ('PURCHASE_INBOUND', 'RETURN_INBOUND') OR qty_delta > 0),
    CONSTRAINT ck_inventory_movements_damage_negative CHECK (
        movement_type <> 'DAMAGE' OR qty_delta < 0),

    -- 报损/盘点必须说明原因（AB-10C：每次调整须留存操作人、原因与前后值）
    CONSTRAINT ck_inventory_movements_reason_required CHECK (
        movement_type NOT IN ('DAMAGE', 'STOCKTAKE')
        OR (reason IS NOT NULL AND length(btrim(reason)) > 0))
);

-- 页面按 SKU 倒序看流水；S-9 取「最近一次采购入库单价」也走这个索引
CREATE INDEX ix_inventory_movements_sku_created
    ON inventory_movements (sku_id, created_at DESC);

COMMENT ON TABLE  inventory_movements IS
    '库存流水（Story 1.4 / AB-10C）。append-only：actual 的每一次变更都必须在此留一行，含前后值与操作人。';
COMMENT ON COLUMN inventory_movements.qty_delta IS
    '带符号增量：入库为正、报损为负、盘点为差值。恒满足 actual_after = actual_before + qty_delta。';
COMMENT ON COLUMN inventory_movements.cost_price IS
    '🔒 进货单价（最小币种单位）。商业敏感：需 shop.cost_view 权限，服务端按权限决定是否下发；审计不记数值。';
COMMENT ON COLUMN inventory_movements.movement_type IS
    'RETURN_INBOUND 为退货入库批次，与采购入库区分——二次销售风险不同（AB-10C / S-9）。';
