-- V1.3.2 batch-a Story 3.5 · 登机牌单张解锁（D-5 / AD-7）。
--
-- 粒度 = 宠物 × 当前场所（UNIQUE (pet_profile_id, place_id)）。卡本身是打卡的聚合、不落库；本表只记「这张卡买没买」。
-- id / public_token 为 AD-7 列表外补充：3-1 的幂等键 {sku}:{业务行 public_token} 与 keepsake_purchases.ref_id 都需要它。
-- 合并场所时由 BoardingPassMergeService 在合并事务内同步改挂（见其矩阵）；superseded 行不删 —— 可能挂着 PENDING / PAID 购买。
-- place_id 对 places 的 FK 无 ON DELETE：场所只软删 / 合并，不物理删。
CREATE TABLE boarding_pass_unlocks (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token   VARCHAR(32)  NOT NULL,
    pet_profile_id BIGINT       NOT NULL,
    place_id       BIGINT       NOT NULL,
    unlocked_at    TIMESTAMPTZ  NULL,
    superseded_at  TIMESTAMPTZ  NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_boarding_pass_unlocks_public_token UNIQUE (public_token),
    CONSTRAINT uq_boarding_pass_pet_place UNIQUE (pet_profile_id, place_id),
    CONSTRAINT fk_boarding_pass_unlocks_pet FOREIGN KEY (pet_profile_id)
        REFERENCES pet_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_boarding_pass_unlocks_place FOREIGN KEY (place_id) REFERENCES places (id)
);

CREATE INDEX idx_boarding_pass_unlocks_superseded ON boarding_pass_unlocks (superseded_at)
    WHERE superseded_at IS NOT NULL;

COMMENT ON TABLE boarding_pass_unlocks IS
    '登机牌单张解锁（V1.3.2 Story 3.5）：宠物 × 当前场所一行。卡是打卡聚合不落库，本表只记是否已买。';
COMMENT ON COLUMN boarding_pass_unlocks.public_token IS '对外不可枚举标识（购买幂等键 / 订单中心跳转）';
COMMENT ON COLUMN boarding_pass_unlocks.place_id IS '当前场所；合并时改挂到保留方（或被 supersede）';
COMMENT ON COLUMN boarding_pass_unlocks.unlocked_at IS '到账发放时刻（UTC）；NULL = 未买';
COMMENT ON COLUMN boarding_pass_unlocks.superseded_at IS
    '非空 = 合并后该行不再代表任何卡；若同时 unlocked_at 非空 = 用户为同一场所付过两次，后台人工退款';
COMMENT ON COLUMN boarding_pass_unlocks.created_at IS '行创建时刻（首次发起购买，UTC）';
