-- V1.4.0 精选自营电商 · Story 7.1 —— 商品评价（FR-106）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。【只建新表】→ 无需群里认领。
-- ⚠️ epics 原文写 V112；按台账「取最大号 +1」实取 V123。
--
-- 🔴【复用既有内容审核机制，同步过滤】：提交时走三方过滤，命中即拦截【不发布】。
--    ⚠️【不走「先发布后审核」】—— 商品评价是带图的公开内容，先发后审意味着违规内容
--    在被发现前对所有潜在买家可见，而它旁边就是我们自己在卖的商品。
--
-- 🔴【每个订单每个 SKU 各评一次】：唯一约束在 shop_order_line_id 上 ——
--    同一 SKU 在一张订单里可能有两行（不同价快照），各自可评；换一张订单也能再评。
--    约束打在 sku_id 上会让「上次买的评过了这次就不能评」，那不是我们要的语义。

CREATE TABLE shop_reviews (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_order_line_id BIGINT       NOT NULL REFERENCES shop_order_lines (id) ON DELETE CASCADE,
    sku_id             BIGINT       NOT NULL REFERENCES shop_skus (id),
    product_id         BIGINT       NOT NULL REFERENCES shop_products (id),
    user_id            BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    rating             SMALLINT     NOT NULL,          -- 1–5，必填
    content            VARCHAR(500),                   -- 选填
    image_keys         VARCHAR(1000),                  -- 选填，≤6 张，objectKey 逗号分隔

    -- 审核结果。PUBLISHED / BLOCKED / PENDING（三方不可用时 fail-closed 的待重试态）
    review_status      VARCHAR(16)  NOT NULL,
    -- 🔒 只记结论与分类，【不记原文】—— 原文已经在 content 列里，重复一份只是多一处泄露面
    moderation_label   VARCHAR(64),
    moderation_score   NUMERIC(4, 3),

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_shop_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_shop_reviews_status CHECK (
        review_status IN ('PUBLISHED', 'BLOCKED', 'PENDING')),
    -- 🔴 每个订单行只能评一次
    CONSTRAINT uq_shop_reviews_order_line UNIQUE (shop_order_line_id)
);

-- 详情页评价区按时间倒序读
CREATE INDEX ix_shop_reviews_product ON shop_reviews (product_id, created_at DESC)
    WHERE review_status = 'PUBLISHED';
CREATE INDEX ix_shop_reviews_user ON shop_reviews (user_id, created_at DESC);
-- 三方降级后的待重试队列
CREATE INDEX ix_shop_reviews_pending ON shop_reviews (created_at)
    WHERE review_status = 'PENDING';

COMMENT ON TABLE shop_reviews IS
    '商品评价（Story 7.1，FR-106）。🔴 同步过滤，命中即拦截不发布；不走先发布后审核。';
COMMENT ON COLUMN shop_reviews.shop_order_line_id IS
    '🔴 唯一约束打在【订单行】上：同一 SKU 换一张订单还能再评，同一订单同一行只能评一次。';
