-- V1.4.0 精选自营电商 · Story 1.2 —— SKU 库存（FR-95）。
-- 工作线：V1.4.0 电商（分支 shawn/oneline-ecommerce）· 独占号段 V101–V139（并行契约 §1）。
-- 本迁移【只建新表，不触碰任何共享表】→ 无需在群里认领。
-- ⚠️ 号必须 > V101（Flyway 默认 outOfOrder=false）；FK 指向 V101 建的 shop_skus，1.1 须先合入。
--
-- 设计要点：
-- · 🔴【可售库存 = actual - locked，查询期计算，绝不落第三列】——三列并存必然出现三值不一致，
--   而库存不一致等于钱不一致。宁可每次多做一次减法。
-- · 🔴 防超卖的唯一防线是【单条条件原子 UPDATE + 判影响行数】，不是应用层「先查再改」。
--   范式照 V1.0 决策 F11（兽医抢单）与 pawcoin_wallets.applyDelta（V61）。
--   禁分布式锁 / 禁 Redis 扣减 / 禁任何新中间件（CLAUDE.md 护栏 NFR-1 · AD-6）。
-- · CHECK 是最后一道兜底：即便应用层写错，DB 也不允许 locked > actual 或出现负数。
-- · 一 SKU 一行（UNIQUE）；SKU 删除时库存行随之消失（ON DELETE CASCADE）。

CREATE TABLE sku_inventory (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id     BIGINT      NOT NULL REFERENCES shop_skus (id) ON DELETE CASCADE,
    actual     BIGINT      NOT NULL DEFAULT 0,   -- 实际库存（仓库里真实有多少）
    locked     BIGINT      NOT NULL DEFAULT 0,   -- 锁定库存（已下单未支付/未出库）
    -- 可售库存 = actual - locked：【不落库】，查询期计算
    version    BIGINT      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_sku_inventory_actual_non_negative CHECK (actual >= 0),
    CONSTRAINT ck_sku_inventory_locked_non_negative CHECK (locked >= 0),
    -- 🔴 不变式：锁定量不得超过实际库存 → 可售库存恒 >= 0，超卖目标为 0（NFR-8）
    CONSTRAINT ck_sku_inventory_locked_le_actual   CHECK (locked <= actual)
);

CREATE UNIQUE INDEX uq_sku_inventory_sku ON sku_inventory (sku_id);

COMMENT ON TABLE  sku_inventory IS
    'SKU 库存（Story 1.2）。可售库存 = actual - locked，查询期计算不落库。';
COMMENT ON COLUMN sku_inventory.locked IS
    '锁定库存：提交订单时 +qty（3.4），支付成功转扣减（3.8），超时/取消释放（3.4）。';
