-- V1.4.0 精选自营电商 · Story 6.3 —— 复购触发记录（FR-109 粮量见底预估）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。
-- ⚠️ epics 原文写 V111；按台账「取最大号 +1」实取 V122。
-- ⚠️⚠️ 【触碰共享 CHECK：ck_notifications_type】——与 V116/V117/V120 同一条约束，须一并认领。
--    依产品【临时授权】（HEX-SIGNOFF §临时授权）照推。
--
-- 🔴【日扫落库，不做请求时实时计算】（AD-12）：实时算需跨订单历史 + 商品喂量 + 档案体重三方 join，
--    放在首页请求路径上不合适。首页与推送读的是【同一份】落库结果，口径天然一致。
--
-- 🔴【trigger_type 保留三值】DEWORM / VACCINE / FOOD_LOW —— 供 1.2.0 FR-108 上线时
--    直接追加数据、不断历史序列。⚠️【本版本只会产生 FOOD_LOW】：FR-108 已移出（C-11）。
--    AB-13B 看板须写明「DEWORM/VACCINE 恒为 0 是范围决策，不是数据丢失」，否则运营会报「埋点坏了」。

CREATE TABLE repurchase_triggers (
    id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    pet_profile_id           BIGINT      NOT NULL REFERENCES pet_profiles (id) ON DELETE CASCADE,
    sku_id                   BIGINT      NOT NULL REFERENCES shop_skus (id),
    -- 触发它的那笔订单（再次购买该 SKU 后据此让旧触发失效）
    source_order_id          BIGINT      REFERENCES shop_orders (id) ON DELETE SET NULL,

    estimated_depletion_date DATE        NOT NULL,
    trigger_type             VARCHAR(16) NOT NULL,
    status                   VARCHAR(16) NOT NULL,
    -- 「推送一次」的落点：推过就记时刻，重算不重推（⚠️ SPEC-16 的语义细节仍未拍板，见 story 文档）
    notified_at              TIMESTAMPTZ,
    dismissed_at             TIMESTAMPTZ,

    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_repurchase_triggers_type CHECK (
        trigger_type IN ('DEWORM', 'VACCINE', 'FOOD_LOW')),
    CONSTRAINT ck_repurchase_triggers_status CHECK (
        status IN ('ACTIVE', 'SUPERSEDED', 'DISMISSED', 'CONVERTED'))
);

-- 🔴 同一 (用户, SKU) 至多一条【进行中】的触发 —— 日扫每天都跑，没有这条会每天多一行。
--    与订单侧同一处置：并发正确性交给库级部分唯一索引，不靠应用层先查后插。
CREATE UNIQUE INDEX uq_repurchase_triggers_active
    ON repurchase_triggers (user_id, sku_id)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_repurchase_triggers_user ON repurchase_triggers (user_id, status);
CREATE INDEX ix_repurchase_triggers_date ON repurchase_triggers (estimated_depletion_date);

-- ---------- 站内推送类型 ----------
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_type;
ALTER TABLE notifications ADD CONSTRAINT ck_notifications_type CHECK (type IN (
    'VET_REPLY', 'CONSULT_CLOSED', 'CONTENT_LIKED', 'CONTENT_COMMENTED', 'NEW_CONSULT_REQUEST',
    'PET_BIRTHDAY', 'COMPANION_ANNIVERSARY', 'MILESTONE_NODE', 'CONTENT_REMOVED', 'REPORT_REVIEWED',
    'CONTENT_REVIEW_APPROVED', 'CONTENT_REVIEW_REJECTED',
    'NAME_RESET', 'AVATAR_RESET', 'CONTENT_REVIEW_TIMED_OUT',
    'REFUND_REJECTED', 'TICKET_RESOLVED', 'CSAT_SURVEY', 'IDENTITY_REQUIRE_MODIFY',
    -- V1.1.4 Story 3.2（V104）账号级处置两值：本条原基于 V97 的 19 值书写，漏抄了它们，
    --   staging 因 notifications 已有此类行而 23514 崩启动。补回 —— 勿再删。
    'ACCOUNT_WARNED', 'ACCOUNT_SUSPENDED',
    'SHOP_ORDER_SHIPPED', 'SHOP_ORDER_EXCEPTION', 'SHOP_RETURN_UPDATED',
    -- V1.4.0 Story 6.3：粮量见底提醒（FR-109）。🔴 复用现有推送通道，不新建提醒引擎。
    'REPURCHASE_FOOD_LOW'));

COMMENT ON TABLE repurchase_triggers IS
    '复购触发（Story 6.3，FR-109）。🔴 日扫落库，首页与推送读同一份结果（AD-12）。'
    '⚠️ 本版本只产生 FOOD_LOW —— DEWORM/VACCINE 恒为 0 是范围决策（C-11），不是数据丢失。';
