-- V1.4.0 精选自营电商 · Story 2.1 —— 收货地址（FR-98）。
-- 工作线：V1.4.0 电商（分支 shawn/oneline-ecommerce）· 独占号段 V101–V139（并行契约 §1）。
-- 本迁移【只建新表，不触碰任何共享表】→ 无需在群里认领。
-- ⚠️ epics 原文写的号是 V103，但 V103 已被 Story 1.3 占用；按台账重排后取 V106。
--
-- 🔒【本表是 App 内首个用户地址 PII 数据集】——NFR-5 的日志禁记项因此新增三项：
--    收件人姓名 / 履约手机号 / 详细地址。已同步扩充 LogSanitizer.SENSITIVE_KEYS。
--
-- 🔴 注销级联处置【本迁移刻意不写死】：OQ-41（注销级联与 UU PDP）待 Legal 拍板，
--    AD-13 要求先建模、留出 ON DELETE 语义的选择空间。故此处 FK 用【默认 NO ACTION】——
--    它既不是 CASCADE 也不是 SET NULL，将来无论拍成哪种都只需一条 ALTER，
--    而现在就写 CASCADE 等于替 Legal 做了决定，且删了就找不回来。

CREATE TABLE shipping_addresses (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 不可枚举对外标识（NFR-3）：绝不外露自增 id
    public_token      VARCHAR(32)  NOT NULL,
    user_id           BIGINT       NOT NULL,

    -- FR-98 九字段 --------------------------------------------------------
    receiver_name     VARCHAR(40)  NOT NULL,   -- 🔒 PII
    -- 🔒 PII。E.164 归一化存储（C-15）：+62 + 9~12 位有效位，首位必为 8。
    -- 🔴【与账号手机号不互通、不自动填充、不同步】——两者用途不同：
    --    账号手机号用于登录与账号安全，履约手机号用于快递员联系收件人，
    --    收件人可以根本不是账号主人（替家人下单在印尼很常见）。
    receiver_phone    VARCHAR(16)  NOT NULL,
    provinsi          VARCHAR(60)  NOT NULL,
    kota_kabupaten    VARCHAR(60)  NOT NULL,
    -- 🔴 运费按 Kecamatan 计（FR-99 一维运费表），服务范围也按它判定 → 是本表最关键的业务字段
    kecamatan         VARCHAR(60)  NOT NULL,
    address_line      VARCHAR(120) NOT NULL,   -- 🔒 PII（详细地址）
    kode_pos          VARCHAR(5)   NOT NULL,
    label             VARCHAR(10),             -- 「Rumah」「Kantor」等，可空
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,

    -- 「删除默认地址后，剩余中最近使用的一条升为默认」需要一个可排序的「最近使用」依据。
    -- 结算选用时更新它；从未用过则为 NULL，回落到 updated_at 排序。
    last_used_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_shipping_addresses_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_shipping_addresses_token UNIQUE (public_token),
    -- E.164 形状在 DB 层也兜一道：应用层归一化写错时不至于静默存进脏号码。
    -- 🔴 下限 9 位（不是 PRD 原文的 8 位）：8 位会放进大量无效号码，
    --    而【无效号 = 快递员联系不上 = 真实履约失败】，这个错的代价由平台承担。
    CONSTRAINT ck_shipping_addresses_phone CHECK (receiver_phone ~ '^\+628[0-9]{8,11}$'),
    CONSTRAINT ck_shipping_addresses_kode_pos CHECK (kode_pos ~ '^[0-9]{5}$')
);

CREATE INDEX ix_shipping_addresses_user ON shipping_addresses (user_id, is_default DESC, id DESC);

-- 🔴 一个用户至多一个默认地址：部分唯一索引比应用层「先清后设」可靠得多——
--    后者在并发下会出现两个默认，而默认地址错了 = 货寄错地方。
CREATE UNIQUE INDEX uq_shipping_addresses_one_default
    ON shipping_addresses (user_id) WHERE is_default;

COMMENT ON TABLE shipping_addresses IS
    '收货地址（Story 2.1 / FR-98）。🔒 App 内首个用户地址 PII 数据集；注销级联待 OQ-41，FK 有意保持 NO ACTION。';
COMMENT ON COLUMN shipping_addresses.receiver_phone IS
    '🔒 履约手机号，E.164 归一化（+62 + 9~12 位，首位 8）。与账号手机号不互通、不自动填充、不同步。';
COMMENT ON COLUMN shipping_addresses.kecamatan IS
    '运费与服务范围的判定粒度（FR-99 一维运费表）。';
