-- 自动评论留档（2026-09-29）：定时任务每天 09:30 / 20:00（WIB）给「发帖超 2 小时、零评论、已过审的公开帖」
-- 用 AI 读首图生成一句评论，以虚拟账号直接发出。每个帖子最多一行 = 最多自动评论一次（post_id 唯一）。
--
-- 状态：
--   POSTED       已发出（comment_id 指向那条评论；评论本身仍走正常的审核链路）
--   AI_SKIPPED   AI 判定不宜评论（非宠物图 / 看不清 / 悲伤内容等），skip_reason 记原因
--   NO_IMAGE     帖子无图（只读首图，纯文字帖不评）
--   NO_IDENTITY  没有可用的虚拟账号（全被作者拉黑 / 全停用）
--   BLOCKED      生成的文字命中 L1 敏感词被拒
--   POST_GONE    生成期间帖子被删 / 下架 / 转私密
--   FAILED       AI 调用或其他异常；attempts 未到上限时下一轮会重试
--
-- 🔒 只存公开信息：首图是公开桶 URL，generated_text 就是公开发出去的评论正文。
--    comment_id / virtual_user_id 不设外键：留档不能挡住评论删除或账号注销。

CREATE TABLE auto_comment_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT       NOT NULL REFERENCES content_posts (id) ON DELETE CASCADE,
    status          VARCHAR(16)  NOT NULL,
    attempts        INTEGER      NOT NULL DEFAULT 1,
    virtual_user_id BIGINT,
    comment_id      BIGINT,
    image_url       VARCHAR(1024),
    model           VARCHAR(64),
    prompt_version  VARCHAR(16),
    generated_text  VARCHAR(400),
    skip_reason     VARCHAR(200),
    error_code      VARCHAR(64),
    latency_ms      INTEGER,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_auto_comment_logs_post UNIQUE (post_id),
    CONSTRAINT ck_auto_comment_logs_status CHECK (status IN
        ('POSTED', 'AI_SKIPPED', 'NO_IMAGE', 'NO_IDENTITY', 'BLOCKED', 'POST_GONE', 'FAILED'))
);

-- 运营按天看留档（created_at 倒序）。
CREATE INDEX ix_auto_comment_logs_created ON auto_comment_logs (created_at DESC);

COMMENT ON TABLE auto_comment_logs IS
    '自动评论留档：每帖至多一行（AutoCommentJob 写入）。记录所用虚拟账号、AI 生成文字、结果状态。';
COMMENT ON COLUMN auto_comment_logs.attempts IS '尝试次数；仅 FAILED 在未达上限时会被下一轮重试';
COMMENT ON COLUMN auto_comment_logs.prompt_version IS '提示词版本号，改提示词时递增，便于对比效果';
