-- Lark 定时发帖（spec-lark-scheduled-posts）：内容编号去重 + 发布状态机。
-- 运营在 Lark 表格《List of Content for Automatic Upload》维护待发内容，后端每小时拉取并
-- 以虚拟账号发布一条；本表按内容编号唯一，保证「发布成功但表格回写失败」的崩溃窗口不双发
-- （下轮命中 PUBLISHED 记录 → 只补回写，不再发帖）。
-- ddl-auto=validate，schema 归 Flyway。UTC。时间戳版本号（决策 E6）。

CREATE TABLE lark_content_publishes (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_code VARCHAR(32)  NOT NULL,                     -- Lark 表「内容编号」（如 DR260823001）
    image_codes  VARCHAR(255),                              -- 「图片编号」原文（逗号分隔多图）
    author_id    BIGINT       NOT NULL,                     -- 随机选中的虚拟账号 users.id
    post_id      BIGINT,                                    -- 发布成功的 content_posts.id；FAILED 为 NULL
    status       VARCHAR(16)  NOT NULL,                     -- PUBLISHED / FAILED
    fail_reason  VARCHAR(255),                              -- FAILED 时的原因摘要（不含敏感信息）
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_lark_content_publishes_code UNIQUE (content_code)
);

COMMENT ON TABLE lark_content_publishes IS 'Lark 定时发帖状态机：内容编号唯一去重，PUBLISHED 记录挡住重复发布';
COMMENT ON COLUMN lark_content_publishes.content_code IS 'Lark 表「内容编号」，全链路幂等锚（幂等键 lark-content:{code}）';
COMMENT ON COLUMN lark_content_publishes.image_codes IS 'Lark 表「图片编号」原文；云盘文件名={编号}.jpg';
COMMENT ON COLUMN lark_content_publishes.post_id IS '发布成功的 content_posts.id；失败为 NULL';
COMMENT ON COLUMN lark_content_publishes.status IS 'PUBLISHED=已发帖（表格可能还欠回写）；FAILED=本行发布失败（运营清空表格状态列可重试）';
COMMENT ON COLUMN lark_content_publishes.fail_reason IS '失败原因摘要，同步回写到表格「上传状态」列';
