-- V20260909_1539__init_warm_reply_followups.sql —— V1.3.0 AB-20A 暖贴回复跟进（AD-6，Story 4.3）
CREATE TABLE warm_reply_followups (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    virtual_comment_id  BIGINT       NOT NULL REFERENCES comments (id) ON DELETE CASCADE,
    post_id             BIGINT       NOT NULL,
    virtual_user_id     BIGINT       NOT NULL,          -- 被回复的虚拟账号（users.id，account_type=VIRTUAL）
    pending_reply_count INT          NOT NULL DEFAULT 1 CHECK (pending_reply_count >= 0),
    last_reply_id       BIGINT,                          -- 最近一条触发入队的真实回复
    last_reply_at       TIMESTAMPTZ,
    status              VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    handled_by          BIGINT,                          -- admin_accounts.id
    handled_at          TIMESTAMPTZ,
    handled_action      VARCHAR(16),                     -- REPLIED | READ
    handled_comment_id  BIGINT,                          -- REPLIED 时运营以虚拟身份发出的回复 id
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_warm_reply_status CHECK (status IN ('PENDING', 'HANDLED')),
    CONSTRAINT ck_warm_reply_action CHECK (handled_action IS NULL OR handled_action IN ('REPLIED', 'READ'))
);
-- 同一虚拟评论只允许一条待跟进项（多条真实回复合并累加）
CREATE UNIQUE INDEX uq_warm_reply_pending ON warm_reply_followups (virtual_comment_id) WHERE status = 'PENDING';
CREATE INDEX ix_warm_reply_status_time ON warm_reply_followups (status, last_reply_at DESC);
COMMENT ON TABLE warm_reply_followups IS '暖贴回复跟进队列：虚拟一级评论收到真实回复即入队；回复被删/下架减计数归零即删；处理后 HANDLED 保留 30 天可回看';
