-- V1.3.2 batch-a · Story 1.2 —— 宠物护照（FR-120，架构 delta AD-6）。
--
-- · 一宠一本：UNIQUE(pet_profile_id)；护照号全局唯一：UNIQUE(passport_no)。
-- · 号源（D-6 / AD-6）：宠物已有 KTP 卡 → 沿用该卡护照号（source=KTP）；否则经 CardNumberService.allocatePassportNo
--   与 KTP 共用 passport_no_counters 新发（source=ISSUED）。只读 id_cards、绝不回写。
-- · 签发时机：首次打开护照页或首次打卡，insert-on-conflict 幂等。
-- · 删档 / 注销：PetPassportDeletionService 在删宠物行之前物理删除（AD-17）。

CREATE TABLE pet_passports (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_profile_id BIGINT       NOT NULL REFERENCES pet_profiles (id),
    passport_no    VARCHAR(12)  NOT NULL,
    source         VARCHAR(8)   NOT NULL,
    issued_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_pet_passports_pet UNIQUE (pet_profile_id),
    CONSTRAINT uq_pet_passports_passport_no UNIQUE (passport_no),
    CONSTRAINT ck_pet_passports_source CHECK (source IN ('KTP', 'ISSUED'))
);

COMMENT ON TABLE pet_passports IS
    '宠物护照（V1.3.2 FR-120）。一宠一本；号源规则见架构 delta AD-6：沿用本宠 KTP 卡护照号或同一计数器新发。'
    '只读 id_cards、不回写；此后新建的 KTP 卡照旧各自发号，不与本表同步。';
COMMENT ON COLUMN pet_passports.passport_no IS '12 位连写 TT+物种2+P+年2+序号5（C-13），与 id_cards.passport_no 同一号段、同一计数器。';
COMMENT ON COLUMN pet_passports.source IS 'KTP = 沿用该宠物 KTP 卡上的护照号；ISSUED = 首次进护照页 / 首次打卡时新发。';
COMMENT ON COLUMN pet_passports.issued_at IS '签发时刻（UTC）。';
