-- V1.4.0 精选自营电商 · Story 3.1 —— 购物车（FR-96）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。本迁移【只建新表】→ 无需群里认领。
-- ⚠️ epics 原文写 V104，但 V104 已被 Story 1.4 占用；按台账重排后取 V108。
--
-- 🔴【单店模型，没有任何店铺/卖家分组字段】——平台自营是唯一卖家（FR-96）。
--    照搬 Shopee 的 shop_id 分组会让购物车、结算、订单三处都多出一层永远只有一个元素的嵌套，
--    而这层嵌套一旦进了 API 契约，前端与后续 Epic 全得跟着它走。
--
-- 🔴【游客无购物车】：cart 与 users 一对一，没有匿名 cart 的表达方式。
--    这是有意的能力缺席——加购是转化漏斗上第一个需要身份的动作（FR-96）。

CREATE TABLE shop_carts (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_shop_carts_user FOREIGN KEY (user_id) REFERENCES users (id),
    -- 一人一车
    CONSTRAINT uq_shop_carts_user UNIQUE (user_id)
);

CREATE TABLE shop_cart_items (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT      NOT NULL REFERENCES shop_carts (id) ON DELETE CASCADE,
    sku_id     BIGINT      NOT NULL REFERENCES shop_skus (id) ON DELETE CASCADE,
    qty        INT         NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 同一 SKU 在一辆车里只有一行（再加购是加数量，不是加行）
    CONSTRAINT uq_shop_cart_items_sku UNIQUE (cart_id, sku_id),
    CONSTRAINT ck_shop_cart_items_qty CHECK (qty > 0)
);

CREATE INDEX ix_shop_cart_items_cart ON shop_cart_items (cart_id, id);

COMMENT ON TABLE shop_carts IS
    '购物车（Story 3.1 / FR-96）。🔴 单店模型：无店铺分组字段；一人一车；游客无车。';
COMMENT ON COLUMN shop_cart_items.qty IS
    '数量。上限受该 SKU 可售库存约束（应用层判定，不落库——库存是会变的）。';
