-- V1.3.0 后台 · Story 5.1 —— 场所内容管理数据模型（AB-17A / AD-5）。
-- 只建新表，不触碰共享表。五表：places / place_photos / place_comments / place_checkins / place_reports。
-- · 对外标识 public_token（Base62 22 位），自增 id 不外露。
-- · 枚举 varchar + CHECK 全集（UPPER_SNAKE）。软删 deleted_at；下架 = status DELISTED；合并 = status MERGED + merged_into_id。
-- · 图片只存 OSS objectKey，不存 URL / 签名 URL。
-- · 五个计数列为反规范化缓存，由服务层同事务维护，合并/删除时重算（Story 5.3）。
-- · place_type / tags 不加 CHECK：值域由 App 分支 FR-112 定，后台 Java 枚举软校验（Dev Notes）。
-- · D-39（2026-09-09 拍板）：加 city（城市名，运营录入 / App 标记时传入）+ idx_places_city_status。
-- · 契约 X-1 / X-3：本表 schema 由后台分支定义，App 分支（FR-112）只读写数据。

CREATE TABLE places (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token        VARCHAR(32)   NOT NULL,
    name                VARCHAR(80)   NOT NULL,
    place_type          VARCHAR(32)   NOT NULL,                 -- 与 App 端类型枚举同名（UPPER_SNAKE），值域由 FR-112 定，本表不加 CHECK 以免两分支撞值
    tags                JSONB         NOT NULL DEFAULT '[]'::jsonb,  -- 宠物友好标签码列表
    description         TEXT,
    city                VARCHAR(60)   NOT NULL,                 -- D-39：城市名（雅加达等），运营录入时填 / 选；App 端标记时由 App 分支传入
    address_text        VARCHAR(255)  NOT NULL,                 -- 文字地址（供用户复制导航）
    lat                 NUMERIC(9,6)  NOT NULL,
    lng                 NUMERIC(9,6)  NOT NULL,
    marked_by_user_id   BIGINT        NOT NULL REFERENCES users (id),   -- 标记人（App 用户或运营身份池账号），不可改
    status              VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    merged_into_id      BIGINT        REFERENCES places (id),
    photo_count         INT           NOT NULL DEFAULT 0,
    comment_count       INT           NOT NULL DEFAULT 0,
    checkin_count       INT           NOT NULL DEFAULT 0,
    recommend_count     INT           NOT NULL DEFAULT 0,
    not_recommend_count INT           NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT ck_places_status CHECK (status IN ('ACTIVE', 'DELISTED', 'MERGED')),
    CONSTRAINT ck_places_merged_ref CHECK (
        (status = 'MERGED' AND merged_into_id IS NOT NULL) OR
        (status <> 'MERGED' AND merged_into_id IS NULL)),
    CONSTRAINT ck_places_no_self_merge CHECK (merged_into_id IS NULL OR merged_into_id <> id),
    CONSTRAINT ck_places_lat CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT ck_places_lng CHECK (lng BETWEEN -180 AND 180),
    CONSTRAINT ck_places_counts CHECK (photo_count >= 0 AND comment_count >= 0 AND checkin_count >= 0
                                       AND recommend_count >= 0 AND not_recommend_count >= 0)
);
CREATE UNIQUE INDEX uq_places_token          ON places (public_token);
CREATE INDEX        idx_places_status_ct     ON places (status, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX        idx_places_name          ON places (lower(name));
CREATE INDEX        idx_places_marked_by     ON places (marked_by_user_id);
CREATE INDEX        idx_places_city_status   ON places (city, status) WHERE deleted_at IS NULL;
COMMENT ON TABLE  places IS '场所（AB-17A / FR-112）。status ACTIVE 上架 | DELISTED 下架（软删，直链落「场所不存在」）| MERGED 已并入 merged_into_id。';
COMMENT ON COLUMN places.public_token IS '对外标识（Base62 22 位，不可枚举），自增 id 不外露。';
COMMENT ON COLUMN places.place_type IS '场所类型（UPPER_SNAKE），值域由 App 端 FR-112 定义，后台软校验，暂不加 CHECK。';
COMMENT ON COLUMN places.tags IS '宠物友好标签码列表（JSON 字符串数组），值域由 App 端定义。';
COMMENT ON COLUMN places.city IS '城市名（D-39），运营录入时填 / 选；App 端标记时由 App 分支传入。';
COMMENT ON COLUMN places.marked_by_user_id IS '标记人：App 用户或运营发布身份池账号（users 表），不是后台账号；不可改。';
COMMENT ON COLUMN places.merged_into_id IS '合并指向：仅 status=MERGED 时非空；App 直链据此跳到保留场所（契约 X-1）。';
COMMENT ON COLUMN places.photo_count IS '反规范化缓存：place_photos 未删行数，服务层同事务维护。';
COMMENT ON COLUMN places.comment_count IS '反规范化缓存：place_comments 未删行数。';
COMMENT ON COLUMN places.checkin_count IS '反规范化缓存：place_checkins 行数。';
COMMENT ON COLUMN places.recommend_count IS '反规范化缓存：place_comments 未删且 attitude=RECOMMEND 的行数。';
COMMENT ON COLUMN places.not_recommend_count IS '反规范化缓存：place_comments 未删且 attitude=NOT_RECOMMEND 的行数。';

CREATE TABLE place_photos (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id          BIGINT       NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    object_key        VARCHAR(255) NOT NULL,                    -- OSS objectKey，非 URL
    uploader_user_id  BIGINT       NOT NULL REFERENCES users (id),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ
);
CREATE INDEX idx_place_photos_place ON place_photos (place_id, created_at) WHERE deleted_at IS NULL;
COMMENT ON TABLE  place_photos IS '场所照片；object_key 只存 OSS objectKey，签名 URL 现签不落库。';

CREATE TABLE place_comments (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id        BIGINT        NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    author_user_id  BIGINT        NOT NULL REFERENCES users (id),
    body            VARCHAR(500)  NOT NULL,
    attitude        VARCHAR(16)   NOT NULL,                     -- 二元态度
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT ck_place_comments_attitude CHECK (attitude IN ('RECOMMEND', 'NOT_RECOMMEND'))
);
CREATE INDEX idx_place_comments_place ON place_comments (place_id, created_at DESC) WHERE deleted_at IS NULL;
COMMENT ON TABLE  place_comments IS '场所评论（带二元态度 RECOMMEND / NOT_RECOMMEND），软删 deleted_at。';

CREATE TABLE place_checkins (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id    BIGINT      NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    checked_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_place_checkins_place ON place_checkins (place_id, checked_at DESC);
CREATE INDEX idx_place_checkins_user  ON place_checkins (user_id, place_id);
COMMENT ON TABLE  place_checkins IS '场所打卡记录（护照章）；合并场所时归并由 App 分支监听 PlaceMergedEvent 实现（契约 X-1）。';

CREATE TABLE place_reports (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id           BIGINT       NOT NULL REFERENCES places (id) ON DELETE CASCADE,
    reporter_user_id   BIGINT       NOT NULL REFERENCES users (id),
    reason_type        VARCHAR(24)  NOT NULL,
    status             VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    handled_by         BIGINT,                                  -- admin_accounts.id（后台账号与 App 用户隔离，不加 FK）
    handled_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_place_reports_status CHECK (status IN ('PENDING', 'DISMISSED', 'ACTIONED')),
    CONSTRAINT ck_place_reports_reason CHECK (reason_type IN
        ('ILLEGAL', 'MISINFO', 'INAPPROPRIATE', 'HARASSMENT', 'DUPLICATE', 'CLOSED', 'OTHER')),
    CONSTRAINT uq_place_reports_reporter_place UNIQUE (place_id, reporter_user_id)   -- 同人对同场所一条，重复举报幂等（照 content_reports）
);
CREATE INDEX idx_place_reports_status ON place_reports (status, created_at);
COMMENT ON TABLE  place_reports IS '场所举报（D-5 独立建表；处置流在 Story 5.4 接进 A1 统一队列）。';
COMMENT ON COLUMN place_reports.reason_type IS '沿用 ReportReason 五值 + 场所特有 DUPLICATE（重复场所）/ CLOSED（已关店），PRD AB-17A ②「用户举报重复类目辅助合并」。';
COMMENT ON COLUMN place_reports.handled_by IS '处理人：admin_accounts.id（后台账号，不加 FK，照 content_reports.handled_by）。';
