-- V1.3.2 batch-a Story 3.4 · 护照快照（一次性解锁的「那一刻的版本」，D-4 / AD-7）。
--
-- 一行 = 一次发起购买时冻结的章列表。版本 = 场所集合：购买判定与读取判定一律按 stamps 里的 placeId
-- 【现算】章集合 hash（PlaceSetHash，沿 merged_into_id 解析到最终场所）；落库的 place_set_hash 只作记录，不参与比较。
-- paid_at 为空 = 未付（可能挂着 PENDING 购买）；非空 = 已买到的版本。删档时由 PetPassportDeletionService 显式删，FK 级联兜底。
CREATE TABLE passport_snapshots (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token   VARCHAR(32)  NOT NULL,
    pet_profile_id BIGINT       NOT NULL,
    stamps         JSONB        NOT NULL,
    stamp_count    INT          NOT NULL,
    place_set_hash CHAR(64)     NOT NULL,
    paid_at        TIMESTAMPTZ  NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_passport_snapshots_public_token UNIQUE (public_token),
    CONSTRAINT fk_passport_snapshots_pet FOREIGN KEY (pet_profile_id)
        REFERENCES pet_profiles (id) ON DELETE CASCADE,
    CONSTRAINT ck_passport_snapshots_stamp_count CHECK (stamp_count >= 1)
);

CREATE INDEX idx_passport_snapshots_pet_paid ON passport_snapshots (pet_profile_id, paid_at DESC);

COMMENT ON TABLE passport_snapshots IS
    '护照快照（V1.3.2 Story 3.4）：发起购买时冻结的一版护照。版本判定按 stamps 现算章集合 hash，place_set_hash 仅作记录。';
COMMENT ON COLUMN passport_snapshots.public_token IS '对外不可枚举标识（回看 / 订单中心跳转）';
COMMENT ON COLUMN passport_snapshots.stamps IS
    '发起购买时冻结的章列表 [{placeId, placeToken, placeName, placeType, firstVisitDate, visitCount}]；placeId 仅供现算 hash，不对外下发';
COMMENT ON COLUMN passport_snapshots.stamp_count IS '冻结时的章数（≥1，无章不出购买）';
COMMENT ON COLUMN passport_snapshots.place_set_hash IS '冻结时的章集合 hash（SHA-256 小写 hex），仅作记录；判定一律现算';
COMMENT ON COLUMN passport_snapshots.paid_at IS '到账发放时刻（UTC）；NULL = 未付';
COMMENT ON COLUMN passport_snapshots.created_at IS '发起（冻结）时刻（UTC）';
