-- V1.3.2 batch-a · Story 3.1 —— 一次性解锁的购买链路与定价（FR-117 / FR-120，架构 delta AD-1 / AD-12 / AD-17，决策 D-2 / D-3）。
--
-- 🔴🔴 **本迁移全量重建共享 CHECK `ck_payment_intents_purpose`。** 🔴🔴
--    同 V20260818_0037 的写法：DROP + ADD 时**显式列全八个值**，本次新增的**只有后三项**
--    （TAILSONALITY / PASSPORT_SNAP / BOARDING_PASS）。并集核查（2026-09-30 开工当天对全部远端分支重跑）：
--    各分支最新重建均为 V20260818_0037 的五值，无其它分支新增取值 —— 故全集 = 5 + 3 = 8。
--
-- 🔴 本迁移不回填、不改写任何既有行。

ALTER TABLE payment_intents DROP CONSTRAINT ck_payment_intents_purpose;
ALTER TABLE payment_intents ADD CONSTRAINT ck_payment_intents_purpose
    CHECK (purpose IN ('VET_CONSULT', 'PAWCOIN_TOPUP', 'AI_UNLOCK', 'ID_HD', 'SHOP_ORDER',
                       'TAILSONALITY', 'PASSPORT_SNAP', 'BOARDING_PASS'));

-- ---------------------------------------------------------------------------
-- 购买记录（AD-1）：三类一次性解锁共用一张购买表；业务行（结果 / 快照 / 登机牌）先于购买存在，ref_id 指向它。
-- ---------------------------------------------------------------------------
CREATE TABLE keepsake_purchases (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token       VARCHAR(32)  NOT NULL,
    sku                VARCHAR(16)  NOT NULL,
    ref_id             BIGINT       NOT NULL,
    pet_profile_id     BIGINT       NULL REFERENCES pet_profiles (id) ON DELETE SET NULL,
    user_id            BIGINT       NOT NULL,
    price_idr          BIGINT       NOT NULL,
    pay_channel        VARCHAR(16)  NOT NULL,
    payment_intent_id  BIGINT       NULL,
    status             VARCHAR(16)  NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    paid_at            TIMESTAMPTZ  NULL,
    CONSTRAINT uq_keepsake_purchases_public_token UNIQUE (public_token),
    CONSTRAINT uq_keepsake_purchases_payment_intent UNIQUE (payment_intent_id),
    CONSTRAINT ck_keepsake_purchases_sku CHECK (sku IN ('TAILSONALITY', 'PASSPORT_SNAP', 'BOARDING_PASS')),
    CONSTRAINT ck_keepsake_purchases_price CHECK (price_idr >= 1),
    CONSTRAINT ck_keepsake_purchases_channel CHECK (pay_channel IN ('QRIS', 'PAWCOIN')),
    CONSTRAINT ck_keepsake_purchases_status CHECK (status IN
        ('PENDING', 'PAID', 'CANCELED', 'EXPIRED', 'DUPLICATE_PAID', 'ORPHAN_PAID'))
);

-- 同一业务行同时只一笔 PENDING（库级兜底）。
CREATE UNIQUE INDEX uq_keepsake_purchases_pending_ref ON keepsake_purchases (sku, ref_id) WHERE status = 'PENDING';
-- 订单中心（Story 3.6）游标。
CREATE INDEX ix_keepsake_purchases_user_created ON keepsake_purchases (user_id, created_at DESC, id DESC);
-- 后台异常筛查（重复付款 / 孤儿付款）。
CREATE INDEX ix_keepsake_purchases_anomaly ON keepsake_purchases (status)
    WHERE status IN ('DUPLICATE_PAID', 'ORPHAN_PAID');

COMMENT ON TABLE keepsake_purchases IS
    '一次性解锁购买记录（V1.3.2 AD-1）：Tailsonality 结果 / 护照快照 / 登机牌三类共用。资金流水，删档与注销都保留'
    '（删档 pet_profile_id 置空；注销随 users 行匿名化口径不删）。';
COMMENT ON COLUMN keepsake_purchases.public_token IS '不可枚举对外标识（订单中心 orderToken，32 位 base62）。';
COMMENT ON COLUMN keepsake_purchases.sku IS 'TAILSONALITY / PASSPORT_SNAP / BOARDING_PASS，与 payment_intents.purpose 同名。';
COMMENT ON COLUMN keepsake_purchases.ref_id IS
    '业务行 id（多态、不加 FK）：TAILSONALITY → tailsonality_results.id；PASSPORT_SNAP → passport_snapshots.id；'
    'BOARDING_PASS → boarding_pass_unlocks.id。';
COMMENT ON COLUMN keepsake_purchases.pet_profile_id IS '购买时的宠物（记录用）；删档置 NULL，购买不丢。';
COMMENT ON COLUMN keepsake_purchases.user_id IS '购买人（照 payment_intents 不加 FK；注销时 users 行匿名化不删）。';
COMMENT ON COLUMN keepsake_purchases.price_idr IS
    '实际成交价（IDR，≥1）：QRIS = 意图金额 / 到账金额；PawCoin = 扣币额。展示、对账、订单中心、仪表盘只读它。';
COMMENT ON COLUMN keepsake_purchases.pay_channel IS '支付渠道：QRIS / PAWCOIN（虚拟商品不支持混合支付）。';
COMMENT ON COLUMN keepsake_purchases.payment_intent_id IS 'QRIS 对应的 payment_intents.id；PawCoin 为 NULL。';
COMMENT ON COLUMN keepsake_purchases.status IS
    'PENDING 待付 / PAID 已付已发放 / CANCELED / EXPIRED / DUPLICATE_PAID 到账时业务行已解锁（交人工退款）/ '
    'ORPHAN_PAID 到账时业务行不存在或发放失败（交人工）。';
COMMENT ON COLUMN keepsake_purchases.paid_at IS '到账 / 扣币时刻（UTC）。';

-- ---------------------------------------------------------------------------
-- 定价（AD-12 / D-3）：新增 Tailsonality 解锁价；护照两列只改 COMMENT、不改值（上线前运营在后台改，发版检查单 RC-1）。
-- ---------------------------------------------------------------------------
ALTER TABLE pricing_config ADD COLUMN tailsonality_unlock_price BIGINT;
UPDATE pricing_config SET tailsonality_unlock_price = 5000;
ALTER TABLE pricing_config ALTER COLUMN tailsonality_unlock_price SET NOT NULL;
ALTER TABLE pricing_config ADD CONSTRAINT ck_pricing_tailsonality_min CHECK (tailsonality_unlock_price >= 1);
COMMENT ON COLUMN pricing_config.tailsonality_unlock_price     IS 'FR-117 Tailsonality · 结果解锁价（IDR，≥1，D-3 不做 0 元）';
COMMENT ON COLUMN pricing_config.passport_page_unlock_price     IS 'FR-120 护照内页 · 每次快照解锁价（IDR，≥1）';
COMMENT ON COLUMN pricing_config.passport_boarding_unlock_price IS 'FR-120 登机牌 · 每张解锁价（IDR，≥1）';
COMMENT ON COLUMN pricing_config.id_hd_download_price           IS 'KTP 卡高清图下载价（IDR，≥1；与护照两价、Tailsonality 同卡「一次性解锁定价」）';
