-- V20260909_1432__init_ops_daily_metrics.sql
-- V1.3.0 AB-15A 数据看板 · Story 3.2（AD-2）。日粒度预聚合长表：一行 = (WIB 自然日, 指标, 口径)。
-- 长表不选 27 列宽表：加指标不改 schema、双口径天然表达、图表按 key 过滤取数。
-- 行一旦物化不再变（口径截止该日 24:00，同一天数字不随后续互动上涨）。
CREATE TABLE ops_daily_metrics (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date  DATE          NOT NULL,                 -- WIB 自然日
    metric_key   VARCHAR(48)   NOT NULL,                 -- DashboardMetric 枚举 18 值（snake_case key）
    scope        VARCHAR(8)    NOT NULL,                 -- ALL | REAL
    value        NUMERIC(18,4) NOT NULL,
    computed_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_ops_daily_metrics_scope CHECK (scope IN ('ALL', 'REAL')),
    CONSTRAINT uq_ops_daily_metrics UNIQUE (report_date, metric_key, scope)
);
CREATE INDEX idx_ops_daily_metrics_date ON ops_daily_metrics (report_date);
COMMENT ON TABLE ops_daily_metrics IS 'AB-15A 看板预聚合：一行一个(日,指标,口径)，历史行不可变；scope=REAL 仅帖子类 9 项。';
