-- V1.4.0 精选自营电商 · Story 5.6 —— 「开封」判定判例库（AB-12D，SPEC-24 / D-4 / OQ-28）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。【只建新表】→ 无需群里认领。
--
-- ⚠️【判例库是一致性工具，不是风控工具】（SPEC-24 原文）。
--    它解决的是「同一情形不同客服判得不一样」；骗退风控由 S-4 的 90 日 ≤2 次频次上限承担。
--    两者不可互相替代 —— 把判例库当风控用，会让 CS 以为「查过判例 = 查过风险」。
--
-- 🔴 首版不引入第三方质检：判定仍由 CS 依凭证图主观进行，本表只沉淀已做过的判断。

CREATE TABLE opened_precedents (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    situation         VARCHAR(300) NOT NULL,        -- 情形描述（检索主依据）
    judged_opened     BOOLEAN      NOT NULL,        -- 判定：是否算「已开封」
    rationale         VARCHAR(1000) NOT NULL,       -- 判定理由（🔴 必填，见实体注释）
    evidence_keys     VARCHAR(1000),                -- 凭证图 key，逗号分隔
    return_request_id BIGINT       REFERENCES return_requests (id) ON DELETE SET NULL,
    created_by        BIGINT       NOT NULL,        -- admin_accounts.id
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_opened_precedents_created ON opened_precedents (created_at DESC);

COMMENT ON TABLE opened_precedents IS
    '开封判定判例（Story 5.6）。⚠️ 一致性工具，非风控工具（SPEC-24）；风控走 S-4 频次上限。';
