-- V1.4.0 精选自营电商 · Story 2.2 —— 服务范围与运费表（FR-99 / 决策 C-14）。
-- 工作线：V1.4.0 电商 · 独占号段 V101–V139。本迁移【只建新表】→ 无需群里认领。
--
-- 🔴【一维运费表】：C-14 已把原「配送方式 × 区域」二维降为一维。
--    配送方式只剩【标准快递 Reguler 2–4 日】一档，Sameday 本版本不做——
--    「同城」是相对发货地而言的，而发货地在两份 PRD 里从未出现；
--    产品选择直接减档，而不是为了保住一个档位去补一整个「发货仓」概念。
--    ⚠️ 因此本表【没有 delivery_method 列】。将来真要加档位，那是加一列 + 改主键，
--       不是现在先留个恒等于 'REGULER' 的列——那种列只会让人误以为多档已经支持。
--
-- 🔴【承运商不是运费维度】：JNE / SiCepat / Anteraja 仍是多家，但只在发货时由运营选择并录单号
--    （Epic 4 AB-11B）。运费由本表决定，与承运商无关，也【不接承运商实时计费 API】（FR-99）。

CREATE TABLE shipping_zones (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 🔴 Kecamatan 是服务范围与运费的唯一判定粒度（与 shipping_addresses.kecamatan 对齐）
    kecamatan       VARCHAR(60)  NOT NULL,
    kota_kabupaten  VARCHAR(60)  NOT NULL,
    provinsi        VARCHAR(60)  NOT NULL,
    -- 固定运费（最小币种单位，IDR 无小数）
    fee             BIGINT       NOT NULL,
    -- 下架某个区域用 active=false 而非删行：删了就丢掉「这个区域曾经可配送、运费是多少」的历史，
    -- 而历史订单的运费需要可追溯（AB-13D 对账）。
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_shipping_zones_kecamatan UNIQUE (kecamatan),
    CONSTRAINT ck_shipping_zones_fee_non_negative CHECK (fee >= 0)
);

CREATE INDEX ix_shipping_zones_active ON shipping_zones (active, kecamatan);

-- 全局配送设置（单例行，范式同 pricing_config / pawcoin_config）
CREATE TABLE shipping_settings (
    id                       SMALLINT     PRIMARY KEY,
    -- 商品小计 ≥ 此值免运费；0 表示不做免运
    free_shipping_threshold  BIGINT       NOT NULL DEFAULT 0,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_shipping_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_shipping_settings_threshold CHECK (free_shipping_threshold >= 0)
);

INSERT INTO shipping_settings (id, free_shipping_threshold) VALUES (1, 0);

COMMENT ON TABLE shipping_zones IS
    '服务范围与一维固定运费表（Story 2.2 / FR-99 / C-14）。无 delivery_method 列——本版本只有 Reguler 一档。';
COMMENT ON COLUMN shipping_zones.active IS
    '下架区域用 false 而非删行：历史订单的运费需可追溯（AB-13D）。';
