-- Story 5.1（管理后台 Epic 5）：问诊异常工单 consult_anomalies（AB-4A）。
-- 实测最大号+1 = V42（V41=扩 notifications.type）。⚠️ story 指示 V38 已过时（V36-V41 已被 4.3/3.2 等占用），
-- 按决策 E2 单调分配取 V42。仅承载会话元数据（NFR5：绝不含 IM 正文/AI 上下文/用户媒体）。
-- 一会话至多一工单（session_id 唯一索引，去重库级兜底）；工单不可删（归档=status RESOLVED）。
CREATE TABLE consult_anomalies (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id           BIGINT       NOT NULL,
    user_id              BIGINT,                          -- 注销匿名化后可空
    vet_id               BIGINT       NOT NULL,
    session_started_at   TIMESTAMPTZ,
    session_ended_at     TIMESTAMPTZ,
    session_status       VARCHAR(16)  NOT NULL,           -- 中断时会话状态快照（INTERRUPTED）
    anomaly_type         VARCHAR(32)  NOT NULL,           -- VET_BANNED
    status               VARCHAR(16)  NOT NULL,           -- OPEN | RESOLVED
    internal_note        TEXT,                            -- 内部备注（用户不可见）
    resolution_image_key VARCHAR(255),                    -- OSS 对象 key（绝不存签名 URL）
    resolved_by          BIGINT,                          -- admin_accounts.id
    resolved_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_consult_anomalies_status CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_consult_anomalies_type   CHECK (anomaly_type IN ('VET_BANNED'))
);

CREATE UNIQUE INDEX uq_consult_anomalies_session ON consult_anomalies (session_id);
CREATE INDEX idx_consult_anomalies_status ON consult_anomalies (status);
CREATE INDEX idx_consult_anomalies_created ON consult_anomalies (created_at);
