-- Story 1.2（V1.1 资金地基）：双分录总账 + PawCoin 钱包 + 用户流水。实测最大号 V47(1.1) + 1 = V48（决策 E2）。
-- ledger_entries append-only(无 updated_at)；金额 BIGINT 最小币种单位；PawCoin 1 koin=Rp1 同单位。
-- 钱包并发非负 = 原子条件 UPDATE + CHECK 兜底；补偿走反向分录不改旧行。
CREATE TABLE ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_group     VARCHAR(36)  NOT NULL,          -- 一次资金事件的一组平衡分录共享
    account         VARCHAR(20)  NOT NULL,          -- CASH_IN|FLOAT_LIABILITY|VET_PAYABLE|VET_PAID|PLATFORM_REVENUE|REFUND_OUT
    direction       VARCHAR(8)   NOT NULL,          -- DEBIT | CREDIT
    amount          BIGINT       NOT NULL CHECK (amount > 0),
    user_id         BIGINT,                         -- 与用户相关的分录带 user_id（对账/浮存统计）
    ref_type        VARCHAR(24),
    ref_id          BIGINT,
    idempotency_key VARCHAR(80)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_ledger_entries_account   CHECK (account   IN ('CASH_IN','FLOAT_LIABILITY','VET_PAYABLE','VET_PAID','PLATFORM_REVENUE','REFUND_OUT')),
    CONSTRAINT ck_ledger_entries_direction CHECK (direction IN ('DEBIT','CREDIT'))
);
CREATE INDEX        idx_ledger_entries_group ON ledger_entries (entry_group);
CREATE INDEX        idx_ledger_entries_user  ON ledger_entries (user_id, account);
CREATE UNIQUE INDEX uq_ledger_entries_idem   ON ledger_entries (idempotency_key, account, direction);  -- 幂等去重

CREATE TABLE pawcoin_wallets (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    balance    BIGINT       NOT NULL DEFAULT 0 CHECK (balance >= 0),   -- 非负不变式库级兜底
    version    BIGINT       NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_pawcoin_wallets_user ON pawcoin_wallets (user_id);

CREATE TABLE pawcoin_transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    delta       BIGINT       NOT NULL,              -- +充值/退回、-消费
    type        VARCHAR(16)  NOT NULL,              -- TOPUP|SPEND|REFUND|BONUS
    ref_type    VARCHAR(24),
    ref_id      BIGINT,
    entry_group VARCHAR(36),                        -- 关联总账
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_pawcoin_txn_type CHECK (type IN ('TOPUP','SPEND','REFUND','BONUS'))
);
CREATE INDEX idx_pawcoin_txn_user ON pawcoin_transactions (user_id, created_at);
