-- 内容审核 story 9（账号违规计数）：按账号+类型的聚合计数器（§4.1）。
-- 仅记录人工判定违规次数，供运营参考 + V2 阈值预留；【仅写只读，不进任何判定链】。
-- 逐条处置审计证据已由 admin_audit_logs 承载，本表只需聚合快照（V1 轻量姿态）。
CREATE TABLE violation_counts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          BIGINT      NOT NULL,           -- 违规内容所属 App 用户 id（users.id）；不加 FK（注销级联次序）
    violation_type      VARCHAR(16) NOT NULL,           -- UPPER_SNAKE 枚举；length>1 规避 Hibernate CHAR(1) 坑
    violation_count     INTEGER     NOT NULL DEFAULT 0, -- 累计人工判定违规次数（仅记录，不驱动逻辑）
    first_violation_at  TIMESTAMPTZ,                    -- 首次计入时间（UTC）
    last_violation_at   TIMESTAMPTZ,                    -- 最近一次计入时间（UTC）
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_violation_counts_account_type UNIQUE (account_id, violation_type),
    CONSTRAINT ck_violation_counts_type CHECK (
        violation_type IN ('POST', 'COMMENT', 'NAME', 'AVATAR')
    )
);

CREATE INDEX idx_violation_counts_account ON violation_counts (account_id);
