-- Story 1.1（V1.1 资金地基）：payment_intents 支付意图表。
-- 原占 V47，因 feat/content-moderation 已在 stag 占 V47-V56、stag 全局到 V59，本版让号从 V60 起（决策 E2 跨分支撞号重排 2026-07-11）。
-- 凭证/网关正文绝不入库；金额用最小币种单位整型(IDR 无小数)；status 枚举 varchar + CHECK；
-- gateway_ref 唯一 = 回调/轮询双通道去重的库级权威兜底（Redis 仅前置）。
CREATE TABLE payment_intents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_token  VARCHAR(32)  NOT NULL,
    user_id       BIGINT       NOT NULL,
    purpose       VARCHAR(16)  NOT NULL,   -- VET_CONSULT | PAWCOIN_TOPUP | AI_UNLOCK | ID_HD
    channel       VARCHAR(16)  NOT NULL,   -- QRIS | DANA | PAWCOIN
    amount        BIGINT       NOT NULL,
    currency      VARCHAR(8)   NOT NULL DEFAULT 'IDR',
    status        VARCHAR(16)  NOT NULL,   -- PENDING | PAID | FAILED | EXPIRED
    gateway_ref   VARCHAR(128),            -- 网关订单号，回调去重
    gateway_meta  JSONB,                   -- 原始快照（脱敏）
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_payment_intents_status  CHECK (status  IN ('PENDING','PAID','FAILED','EXPIRED')),
    CONSTRAINT ck_payment_intents_purpose CHECK (purpose IN ('VET_CONSULT','PAWCOIN_TOPUP','AI_UNLOCK','ID_HD')),
    CONSTRAINT ck_payment_intents_channel CHECK (channel IN ('QRIS','DANA','PAWCOIN'))
);
CREATE UNIQUE INDEX uq_payment_intents_token       ON payment_intents (public_token);
CREATE UNIQUE INDEX uq_payment_intents_gateway_ref ON payment_intents (gateway_ref);
CREATE INDEX        idx_payment_intents_user       ON payment_intents (user_id);
CREATE INDEX        idx_payment_intents_status     ON payment_intents (status);
