-- Story 2.1（V1.1 Epic 2 开篇）：AI 问诊详情每月免费解锁额度。一人一月一行，used_count 原子递增不超发。
-- 接 1-6 的 V62 顺延（原架构示例号 V48 作废：跨分支撞号 + 1-6 占 V62，决策 E2「实际 merge 时号单调顺延」）。
-- period = YYYY-MM 按 WIB（Asia/Jakarta）算——刻意偏离项目全局 UTC 惯例（免费额度「每月 1 号刷新」对印尼
-- 用户须为本地时间，架构 §调度④）；换月即新行 = 惰性重置，不需 @Scheduled。used_count 非负 CHECK 兜底。
CREATE TABLE user_monthly_free_quota (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    period     VARCHAR(7)   NOT NULL,               -- YYYY-MM（WIB）
    used_count INT          NOT NULL DEFAULT 0 CHECK (used_count >= 0),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_user_monthly_free_quota ON user_monthly_free_quota (user_id, period);
