-- Story 2.3（V1.1 Epic 2）：AI 问诊付费解锁的已结算订单。独立 ID 命名空间（AB-8G，与兽医 consult_orders 隔离）。
-- 接 2-2 的 V64 顺延 V65（决策 E2：新表新迁移，单调顺延）。仅付费路径（PAWCOIN/QRIS/DANA）建订单；
-- 免费额度解锁不建订单（triage_tasks.unlock_source=FREE_QUOTA 即记录）。
--
-- status 相对架构（COMPLETED/ABNORMAL）增 PENDING_PAYMENT：现金（QRIS/DANA）异步到账前的锚态，
-- 供 Midtrans 回调按 payment_intent_token 反查订单拿 triage_task_id 去解锁（PaymentIntent 不带解锁目标，
-- 关联锚落本表，不改 pay 模块）。PAWCOIN 站内扣同步直接 COMPLETED（payment_intent_token 为 null）。
-- ABNORMAL = 到账但订单缺失/triage 已被其它路径解锁/金额异常等对账态（处理器记录不 crash，供 9-x 对账）。
-- order_token/payment_intent_token 用 CardTokenGenerator 生成的 22 位 base62（不可枚举）。金额落成交快照。
CREATE TABLE ai_consult_orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_token          VARCHAR(32)  NOT NULL,               -- 不可枚举对外订单号
    user_id              BIGINT       NOT NULL,
    triage_task_id       BIGINT       NOT NULL,               -- 被解锁的分诊任务
    amount               BIGINT       NOT NULL,               -- 成交价快照（防日后调价影响历史）
    pay_channel          VARCHAR(16)  NOT NULL,               -- QRIS | DANA | PAWCOIN
    payment_intent_token VARCHAR(32),                         -- 现金路径关联 payment_intents；PawCoin 为 null
    status               VARCHAR(16)  NOT NULL,               -- PENDING_PAYMENT | COMPLETED | ABNORMAL
    paid_at              TIMESTAMPTZ,                          -- 到账时间（COMPLETED 时置）
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_ai_consult_orders_channel CHECK (pay_channel IN ('QRIS', 'DANA', 'PAWCOIN')),
    CONSTRAINT ck_ai_consult_orders_status  CHECK (status IN ('PENDING_PAYMENT', 'COMPLETED', 'ABNORMAL'))
);
CREATE UNIQUE INDEX uq_ai_consult_orders_order_token ON ai_consult_orders (order_token);
-- 现金订单一 intent 一单（幂等锚）；PawCoin 订单 payment_intent_token 为 null 不入此唯一约束（部分索引）。
CREATE UNIQUE INDEX uq_ai_consult_orders_intent ON ai_consult_orders (payment_intent_token)
    WHERE payment_intent_token IS NOT NULL;
CREATE INDEX idx_ai_consult_orders_triage ON ai_consult_orders (triage_task_id);
