-- Story 3.1（V1.1 Epic 3 开篇）：兽医咨询计费 A-5 两表拆分。接 2-3 的 V65 顺延 V66（决策 E2 单调顺延；
-- 原架构示例 V49 一把建含 ai_consult_orders，已由 2-3 单独占 V65 拆出，本 story 建余下三表）。
-- 全新表，不碰既有 consult_sessions（V14，免费会话）/failed_consult_requests（V37）。VARCHAR≥16 无 CHAR(1) 坑。
--
-- consult_requests：付费前临时态，state 单列 compare-and-set（H-4，accept/cancel 竞态非时间戳比较）。
--   仅两活态 QUEUEING/ACCEPTED_AWAIT_PAY；取消/超时=物理删行、无 CANCELLED 态（A-5「订单中心无已取消」根因）。
CREATE TABLE consult_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_token     VARCHAR(32)  NOT NULL,                 -- 不可枚举
    user_id           BIGINT       NOT NULL,
    pet_profile_id    BIGINT       NOT NULL,
    vet_id            BIGINT,                                 -- 接单前 null
    state             VARCHAR(24)  NOT NULL,                 -- QUEUEING | ACCEPTED_AWAIT_PAY
    queue_deadline_at TIMESTAMPTZ,                            -- 入队 1min（服务端权威）
    pay_deadline_at   TIMESTAMPTZ,                            -- 接单后 +1.5min
    paused_at         TIMESTAMPTZ,                            -- 跳充值暂停锚（A-4 暂停顺延）
    rebroadcast_count INT          NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_consult_requests_state CHECK (state IN ('QUEUEING', 'ACCEPTED_AWAIT_PAY'))
);
CREATE UNIQUE INDEX uq_consult_requests_token ON consult_requests (request_token);
CREATE INDEX idx_consult_requests_state ON consult_requests (state); -- 供 @Scheduled 扫超时（3-3/3-4）

-- consult_orders：支付成功才建、持久、进订单中心。status 无 CANCELLED（未扣费不建单，A-5）。
--   金额/分成/单价成交时快照（后台 9-2 改价不影响历史）。refund_rejected（A-2 驳回回落 COMPLETED 置真）。
CREATE TABLE consult_orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_token             VARCHAR(32)  NOT NULL,            -- 不可枚举
    user_id                 BIGINT       NOT NULL,
    vet_id                  BIGINT       NOT NULL,
    pet_profile_id          BIGINT       NOT NULL,
    status                  VARCHAR(16)  NOT NULL,            -- IN_PROGRESS | COMPLETED | REFUNDING | REFUNDED（无 CANCELLED）
    amount                  BIGINT       NOT NULL,            -- IDR 最小单位
    pay_channel             VARCHAR(16),                      -- QRIS | DANA | PAWCOIN
    payment_intent_id       BIGINT,                           -- 关联 payment_intents（3-4 落）
    vet_payout              BIGINT,                           -- 分成快照（如 Rp30,000）
    vet_share_rate_snapshot INT,                              -- 分成比例快照（如 60）
    unit_price_snapshot     BIGINT,                           -- 单价快照（如 Rp50,000）
    refund_rejected         BOOLEAN      NOT NULL DEFAULT false,
    session_started_at      TIMESTAMPTZ,
    session_ended_at        TIMESTAMPTZ,
    paid_at                 TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_consult_orders_status  CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'REFUNDING', 'REFUNDED')),
    CONSTRAINT ck_consult_orders_channel CHECK (pay_channel IS NULL OR pay_channel IN ('QRIS', 'DANA', 'PAWCOIN'))
);
CREATE UNIQUE INDEX uq_consult_orders_token ON consult_orders (order_token);

-- consult_order_stage_events：每个节点一行 INSERT，append-only（对账/审计留痕，绝不 UPDATE/DELETE 旧行）。
CREATE TABLE consult_order_stage_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consult_order_id BIGINT       NOT NULL,
    event_type       VARCHAR(24)  NOT NULL,
    occurred_at      TIMESTAMPTZ  NOT NULL,
    note             VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_consult_order_stage_events_type CHECK (event_type IN (
        'ACCEPTED', 'PAID', 'SESSION_STARTED', 'SESSION_ENDED',
        'REFUND_REQUESTED', 'REFUND_COMPLETED', 'REFUND_REJECTED'))
);
CREATE INDEX idx_consult_order_stage_events_order ON consult_order_stage_events (consult_order_id);
