-- Story 3.7：兽医月度结算表。接 3-1 的 V67（tighten_pay_channel）顺延 V68（决策 E2 单调顺延）。
-- ⚠️ 移动靶：stag/其它分支可能已占更高号，merge 时按当时全局 max 再顺延。VARCHAR≥7 无 CHAR(1) 坑。
--
-- 每月 1 日 WIB @Scheduled 生成上月月结（聚合 COMPLETED 订单的 vet_payout 快照）。period 用 WIB（Asia/Jakarta）
--   YYYY-MM——刻意偏离全局 UTC（印尼「每月 1 号」本地语义，架构 §调度④，照 2-1 user_monthly_free_quota）。
-- status：PENDING（生成即待结算）→ SETTLED（管理端 9-5 对账打款后标记）；本 story 只产 PENDING。
-- 金额 bigint IDR 最小单位，非负 CHECK 兜底。唯一 (vet_id, period) → 月结生成幂等去重（重跑不重复）。
CREATE TABLE vet_settlements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vet_id         BIGINT       NOT NULL,
    period         VARCHAR(7)   NOT NULL,                 -- YYYY-MM（WIB）
    order_count    INT          NOT NULL DEFAULT 0 CHECK (order_count >= 0),
    gross_amount   BIGINT       NOT NULL DEFAULT 0 CHECK (gross_amount >= 0),   -- 成交额合计 IDR
    payout_amount  BIGINT       NOT NULL DEFAULT 0 CHECK (payout_amount >= 0),  -- 到手合计 IDR（Σ vet_payout 快照）
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    generated_at   TIMESTAMPTZ  NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_vet_settlements_status CHECK (status IN ('PENDING', 'SETTLED'))
);
CREATE UNIQUE INDEX uq_vet_settlements_vet_period ON vet_settlements (vet_id, period);
CREATE INDEX idx_vet_settlements_vet ON vet_settlements (vet_id); -- 收入页历史查询按 vet
