-- Story 4.1（V1.1 Epic 4 开篇）：客服工单模型升级。接 3-8 的 V69 顺延 V70（决策 E2 单调顺延；
-- 移动靶：merge 时按当时全局 max 再顺延）。
-- ⚠️ 现状（已核实）：**无既有客服工单表**——V1.0「帮助反馈」仅表单/WhatsApp 跳转（PRD line 588），无落库工单。
--   故架构 §3.6「ALTER 既有客服工单表 或 新建 feedback_tickets」在本仓 = **新建**（非 ALTER）。标题「模型升级」
--   = 从 V1.0 无工单升级到真工单系统。同构范式 = moderation.content_reports（用户建 + admin 处理 + status）。
-- CSAT/cs_rating 本 story 只**预留列**（4-7 结案后填/发；cs_rating AB-5G 后续版本），避免二次迁移。
-- VARCHAR≥16 无 CHAR(1) 坑；smallint/bool 非长度=1 varchar，无 CHAR(1) 坑。

-- feedback_tickets：客服工单主表。用户建（OPEN）→ admin 流转（IN_PROGRESS/RESOLVED/CLOSED，4-4/4-7）。
CREATE TABLE feedback_tickets (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_token           VARCHAR(32)  NOT NULL,                 -- 不可枚举（CardTokenGenerator）
    user_id                BIGINT       NOT NULL,
    subject                VARCHAR(200),                          -- 主题，可空（body 必填）
    body                   TEXT         NOT NULL,                 -- 投诉正文
    contact_type           VARCHAR(16)  NOT NULL,                 -- EMAIL | WHATSAPP（自填联系方式）
    contact_value          VARCHAR(255) NOT NULL,                 -- 联系方式值（PII，绝不记日志）
    need_contact_customer  BOOLEAN      NOT NULL DEFAULT true,    -- 用户是否要求客服联系
    contacted_customer     BOOLEAN      NOT NULL DEFAULT false,   -- 客服是否已联系（admin 4-4 置真）
    related_order_id       BIGINT,                                -- 关联 consult_orders（可空；退款工单 4-3 用）
    status                 VARCHAR(16)  NOT NULL DEFAULT 'OPEN',  -- OPEN | IN_PROGRESS | RESOLVED | CLOSED
    -- ↓↓↓ 预留列（本 story 不填不发；4-7 结案后 CSAT，AB-5G cs_rating 后续）↓↓↓
    csat_score             SMALLINT,                              -- 1-5，4-7 填
    csat_comment           VARCHAR(100),                          -- 4-7 填
    csat_deadline          TIMESTAMPTZ,                           -- 4-7 填
    cs_rating              SMALLINT,                              -- AB-5G 后续
    handled_by             BIGINT,                                -- admin，4-4 填
    resolved_at            TIMESTAMPTZ,                           -- 4-4 填
    -- ↑↑↑ 预留列 ↑↑↑
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_feedback_tickets_contact_type CHECK (contact_type IN ('EMAIL', 'WHATSAPP')),
    CONSTRAINT ck_feedback_tickets_status       CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    CONSTRAINT ck_feedback_tickets_csat_score   CHECK (csat_score IS NULL OR csat_score BETWEEN 1 AND 5)
);
CREATE UNIQUE INDEX uq_feedback_tickets_token ON feedback_tickets (ticket_token);
CREATE INDEX idx_feedback_tickets_user ON feedback_tickets (user_id, created_at DESC); -- 我的工单列表

-- ticket_attachments：工单附件，仅存 OSS object_key（复用 shared/media 预签名上传，展示时 SignedUrlService 现签）。
CREATE TABLE ticket_attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id    BIGINT       NOT NULL REFERENCES feedback_tickets (id),
    object_key   VARCHAR(512) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_ticket_attachments_ticket ON ticket_attachments (ticket_id);

-- ticket_labels：工单标签（多选，去重）。唯一 (ticket_id, label) 防重复贴同标签。
CREATE TABLE ticket_labels (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id    BIGINT       NOT NULL REFERENCES feedback_tickets (id),
    label        VARCHAR(24)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_ticket_labels_label CHECK (label IN (
        'BUG', 'FEATURE', 'CONSULT_COMPLAINT', 'REFUND', 'CONTENT', 'ACCOUNT', 'PRAISE', 'OTHER'))
);
CREATE UNIQUE INDEX uq_ticket_labels_ticket_label ON ticket_labels (ticket_id, label);

-- ticket_internal_notes：客服内部备注，**用户绝不可见**（AB-5 隐私契约红线，SupportTicketView 无此字段）。
--   admin 加（addInternalNote 原语本 story 建，UI 在 4-4/4-7）。
CREATE TABLE ticket_internal_notes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id    BIGINT       NOT NULL REFERENCES feedback_tickets (id),
    admin_id     BIGINT       NOT NULL,
    note         TEXT         NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_ticket_internal_notes_ticket ON ticket_internal_notes (ticket_id);
