-- Story 4.3（V1.1 Epic 4，全系统最高危 A-1）：退款申请与两段审批模型。接 4-1 的 V70 顺延 V71
-- （决策 E2 单调顺延；移动靶：merge 时按当时全局 max 再顺延）。
-- ⚠️ V1.0 是零资金系统，无既有退款表 → **新建**。
-- 两段分离：①退款需求判定（客服 submitter，need_decision）②退款申请审批（主管 approver + 财务 payer，approval_status）。
-- 职责分离（A-1）：submitter/approver/payer 两两不可相等（服务层强制，含 SUPER_ADMIN 不豁免）。
-- payout PII（payout_account/account_holder_name）**落库加密密文**（AES-GCM，EncryptedStringConverter），绝不入日志。
-- 实际打款（Midtrans Iris）/ 订单回落 / 通知 / App UI 均不在本 story（4-4/4-5/4-6）。VARCHAR≥16 无 CHAR(1) 坑。

CREATE TABLE refund_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_token        VARCHAR(32)  NOT NULL,                       -- 不可枚举（CardTokenGenerator）
    -- ON DELETE CASCADE：生产 consult_orders 永不删（财务记录），FK 保引用完整；测试清理删订单时级联清退款请求。
    order_id            BIGINT       NOT NULL REFERENCES consult_orders (id) ON DELETE CASCADE,  -- 一订单一退款
    -- 退款请求可脱离工单存续（工单删除仅解绑，不删退款）。
    related_ticket_id   BIGINT       REFERENCES feedback_tickets (id) ON DELETE SET NULL,        -- FR-52（可空）
    user_id             BIGINT       NOT NULL,
    -- ① 第一段「退款需求判定」（客服，AB-5B）
    need_decision       VARCHAR(16)  NOT NULL DEFAULT 'PENDING',     -- PENDING | APPROVED | REJECTED
    submitter_admin_id  BIGINT,                                      -- 客服（判定人）
    -- ② 第二段「退款申请审批」（主管 + 财务，AB-5E）
    approval_status     VARCHAR(20),                                 -- PENDING_APPROVAL|APPROVED|REJECTED|PROCESSING|DONE
    approver_admin_id   BIGINT,                                      -- 主管（审批人）
    payer_admin_id      BIGINT,                                      -- 财务（打款人）
    -- 金额（net 后端权威：net = order_amount − channel_fee，落库快照）
    order_amount        BIGINT       NOT NULL,                       -- 成交时订单金额快照
    channel_fee         BIGINT       NOT NULL DEFAULT 0,             -- 出款渠道费（BCA0/OVO2500/GoPay2500）
    net_amount          BIGINT       NOT NULL DEFAULT 0,             -- 到手净额（选定渠道后算，4-5/4-6）
    -- 收款账户（敏感 PII：payout_account/account_holder_name 加密密文；payout_channel 枚举非 PII 不加密）
    payout_channel      VARCHAR(16),                                 -- BCA | OVO | GOPAY
    payout_account      VARCHAR(512),                                -- 加密密文（AES-GCM base64）
    account_holder_name VARCHAR(512),                                -- 加密密文（AES-GCM base64）
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_refund_requests_need_decision  CHECK (need_decision IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_refund_requests_approval       CHECK (approval_status IS NULL OR approval_status IN (
        'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'PROCESSING', 'DONE')),
    CONSTRAINT ck_refund_requests_payout_channel CHECK (payout_channel IS NULL OR payout_channel IN (
        'BCA', 'OVO', 'GOPAY'))
);
CREATE UNIQUE INDEX uq_refund_requests_token ON refund_requests (refund_token);
CREATE UNIQUE INDEX uq_refund_requests_order ON refund_requests (order_id); -- 防重复退款（一订单一请求）
