-- Story 6.3（V1.1 Epic 6）：身份证高清图一次性永久付费解锁（FR-49D）。
-- 接 V74（6-1 serial）顺延 → V75（架构旧稿「V55 init_id_hd」已作废：与 serial 合并的旧计划，决策 E2 顺延）。
-- payment_intents 表 + ID_HD purpose 早在 V47/init 建好，本迁移只建购买记录表。
-- 一次性永久：UNIQUE(user_id) 一账号至多一行（既是「一次购买永久解锁」语义，也是幂等终极兜底）。
-- pet_profile_id ON DELETE SET NULL：删档/注销后购买行仍在（永久解锁不丢），且不阻断删档（勿设 CASCADE）。
-- ddl-auto=validate，schema 归 Flyway。

CREATE TABLE id_card_hd_purchases (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    pet_profile_id    BIGINT,                                    -- 购买时的宠物（记录用）；删档置 NULL，购买不丢
    pay_channel       VARCHAR(16)  NOT NULL,                     -- QRIS / PAWCOIN（UPPER_SNAKE）
    payment_intent_id BIGINT,                                    -- QRIS 溯源（PawCoin 即时扣费为 NULL）
    purchased_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),       -- UTC
    CONSTRAINT uq_id_card_hd_purchases_user UNIQUE (user_id),    -- 一次性永久 + 幂等兜底
    CONSTRAINT ck_id_card_hd_purchases_channel CHECK (pay_channel IN ('QRIS', 'PAWCOIN')),
    CONSTRAINT fk_id_card_hd_purchases_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_id_card_hd_purchases_pet FOREIGN KEY (pet_profile_id)
        REFERENCES pet_profiles (id) ON DELETE SET NULL
);
