-- Story 7.1（V1.1 Epic 7）：成长档案结构化健康记录（疫苗/驱虫/月经/绝育/自定义，FR-45/45A）。
-- 接 V75（6-3 id_card_hd_purchases）顺延 → V76（架构旧稿「V56 init_health_records」已作废，决策 E2 顺延）。
-- 区别既有 health_events（V5 问诊存档+健康图）：本表是用户手动录入的结构化记录；问诊类不入本表（7-2 只读混排）。
-- 健康数据=PII：日志严禁落明文。档案删除级联硬删（PDP，注销级联延伸 architecture §9）。ddl-auto=validate。

CREATE TABLE health_records (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_profile_id BIGINT       NOT NULL,
    type           VARCHAR(16)  NOT NULL,                 -- VACCINE/DEWORM/MENSTRUATION/NEUTER/CUSTOM
    custom_name    VARCHAR(20),                           -- CUSTOM 必填（自定义记录名）
    vaccine_name   VARCHAR(30),                           -- VACCINE 可选（疫苗名）
    event_date     DATE         NOT NULL,                 -- 发生日期（不可未来、无下限；用户本地日期语义）
    note           VARCHAR(100),                          -- 备注
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),   -- UTC
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),   -- UTC
    CONSTRAINT ck_health_records_type CHECK (type IN ('VACCINE', 'DEWORM', 'MENSTRUATION', 'NEUTER', 'CUSTOM')),
    -- PDP 级联硬删 + 不阻断删档（勿设 RESTRICT，否则删档被阻）。
    CONSTRAINT fk_health_records_pet FOREIGN KEY (pet_profile_id)
        REFERENCES pet_profiles (id) ON DELETE CASCADE
);

-- 列表倒序（按发生日期 desc，同日按 id desc 稳定）。
CREATE INDEX ix_health_records_pet_date ON health_records (pet_profile_id, event_date DESC, id DESC);
