-- Story 6-7（bug 20260721-344 返工）：身份证卡快照表。每张卡=一次锁定的信息快照 + 独立 serial。
-- 决策①卡快照 ②每卡新号 ③旧卡保留可看可下载 ④独立建卡器（卡信息与档案解耦）。
-- 解锁绑 card_id（V92 改 id_card_hd_purchases）。ddl-auto=validate，schema 归 Flyway。UTC。
--
-- serial_id：每卡从既有号池 pet_serial_seq/pet_serial_pool（SerialAllocationService）取一个新号，
--   与 pet_profiles.serial_id 同源不撞；两处 UNIQUE 各自独立。
-- avatar_url：直接存快照当时的公开 OSS URL（public 桶稳定 URL，渲染即用，无需再签名）。

CREATE TABLE id_cards (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    serial_id   BIGINT       NOT NULL,
    name        VARCHAR(60)  NOT NULL,
    pet_type    VARCHAR(16),                              -- 枚举 UPPER_SNAKE（DOG/CAT/...），可空
    breed       VARCHAR(80),
    birthday    DATE,
    avatar_url  VARCHAR(1024),                            -- 快照当时头像公开 URL
    intro       VARCHAR(30),
    hd_unlocked BOOLEAN      NOT NULL DEFAULT false,      -- 本卡 HD 是否已解锁（购买到账置 true）
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_id_cards_serial UNIQUE (serial_id),
    CONSTRAINT fk_id_cards_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 历史列表：某用户全部卡 createdAt 倒序。
CREATE INDEX ix_id_cards_user_created ON id_cards (user_id, created_at DESC);
