-- 两条工作线合并修正（feat/content-moderation × v1.1-dev 合入 main，2026-07-30）：
-- ck_notifications_type 被两线各自 DROP+ADD——审核线 V53 加 NAME_RESET/AVATAR_RESET/
-- CONTENT_REVIEW_TIMED_OUT（V50/V51/V53 递进），v1.1 线 V72 加 REFUND_REJECTED/TICKET_RESOLVED/
-- CSAT_SURVEY/IDENTITY_REQUIRE_MODIFY。合并时间线里 V72 后跑，其 CHECK 列表不含审核线三值 →
-- 发 NAME_RESET/AVATAR_RESET/CONTENT_REVIEW_TIMED_OUT 会违反约束（审核通知全断）。
-- 两线迁移均已冻结（决策 E2），本迁移取【并集】重建约束，为合并库的最终权威列表。
ALTER TABLE notifications DROP CONSTRAINT ck_notifications_type;
ALTER TABLE notifications ADD CONSTRAINT ck_notifications_type CHECK (type IN (
    'VET_REPLY', 'CONSULT_CLOSED', 'CONTENT_LIKED', 'CONTENT_COMMENTED', 'NEW_CONSULT_REQUEST',
    'PET_BIRTHDAY', 'COMPANION_ANNIVERSARY', 'MILESTONE_NODE', 'CONTENT_REMOVED', 'REPORT_REVIEWED',
    'CONTENT_REVIEW_APPROVED', 'CONTENT_REVIEW_REJECTED',
    'NAME_RESET', 'AVATAR_RESET', 'CONTENT_REVIEW_TIMED_OUT',
    'REFUND_REJECTED', 'TICKET_RESOLVED', 'CSAT_SURVEY', 'IDENTITY_REQUIRE_MODIFY'));
